### ISSUE TITLE
Directories where the data is written

### ISSUE THREAD

**Issue by bpierre** [aeternity/testnet#100]
Hi, I am creating a Docker image to make it easier to get the testnet running.

Could you list the directories where any persistent data (blockchain, account, other things) is written?

Thanks!

**Comment by Zwilla** [comment]
I think
* backup
* blocks
* data
* bets
* external_web 
* web

If I’m right, we can close this issue!

**Note that this is under development and will likely!**

**Comment by zack-bitcoin** [comment]
Data
Blocks
Oracle_questions

I think someone else is already working on docker. Have a look at the other pull requests.

**Comment by bpierre** [comment]
Thanks @zack-bitcoin, I added a comment: https://github.com/aeternity/testnet/pull/56#issuecomment-305023295
