### ISSUE TITLE
Testnet en Windows 10

### ISSUE THREAD

**Issue by Leonyxtested** [aeternity/testnet#102]
Se puede descargar he intalar el testnet perfectamente en Windows 10 usando el Bash de Ubuntu, hay un problema con chalang,creo que no es amigable con Windows o la version aun no se ha depurado.

==> encrypter (get-deps)
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> encrypter (compile)
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
/home/ubuntu/testnet/deps/chalang/src/chalang.erl:92: syntax error before: '{'
/home/ubuntu/testnet/deps/chalang/src/chalang.erl:110: syntax error before: '{'
/home/ubuntu/testnet/deps/chalang/src/chalang.erl:2: function data_maker/7 undefined
/home/ubuntu/testnet/deps/chalang/src/chalang.erl:2: function test/6 undefined
/home/ubuntu/testnet/deps/chalang/src/chalang.erl:86: function test/6 undefined
/home/ubuntu/testnet/deps/chalang/src/chalang.erl:80: Warning: function make_tuple/2 is unused
/home/ubuntu/testnet/deps/chalang/src/chalang.erl:82: Warning: function make_list/3 is unused
/home/ubuntu/testnet/deps/chalang/src/chalang.erl:478: Warning: variable 'D' is unused
Compiling /home/ubuntu/testnet/deps/chalang/src/chalang.erl failed:
ERROR: compile failed while processing /home/ubuntu/testnet/deps/chalang: rebar_abort
Erlang R16B03 (erts-5.10.4) [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V5.10.4  (abort with ^G)
1> {"init terminating in do_boot",{undef,[{serve,pw,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,569}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,118}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

P.D: Eliminalo despues de verlo,es mas facil que leas esto por este canal.

**Comment by zack-bitcoin** [comment]
It is because you are using erlang version 16.
The testnet requires version 18 or higher.

Es porque usas version 16. Necesitas version 18 o mas grande.
