### ISSUE TITLE
Account does not exist yet.

### ISSUE THREAD

**Issue by simonpbond** [aeternity/testnet#103]
Hi Zack,

I install, run keys:new("xxxxxx"), keys:unlock("xxxxxx") 
Then check: keys:id(). and keys:address(). 

ID returns a positive value, address returns an address.

Then begin mining.

Then when checking balance with: easy:balance().
I receive a message saying the account does not exist yet.

Am I missing something here?

**Comment by zack-bitcoin** [comment]
It takes 200 blocks for a block reward to mature.

**Comment by simonpbond** [comment]
@zack-bitcoin Thanks :)
Can now see a balance of about 1000 billion, lol.

**Comment by zack-bitcoin** [comment]
Completely reinstalling should fix it.
I fixed a bug today that was making all the accounts reuse the first 16 account locations in the databasend.

**Comment by simonpbond** [comment]
Hey Zack, thanks! Will give it another try.
