### ISSUE TITLE
La variable no se ha utilizado

### ISSUE THREAD

**Issue by Leonyxtested** [aeternity/testnet#107]
Al instalar el testnet con install.sh aparecen advertencias de variables que no se usan,he podido rescatar esto,el buffer es mas corto en Ubuntu:

Compiled src/consensus/sync.erl
Compiled src/consensus/packer.erl
src/consensus/secrets.erl:51: Warning: function old_new_lightning/0 is unused
src/consensus/secrets.erl:57: Warning: function test_new_lightning/0 is unused
Compiled src/consensus/secrets.erl
Compiled src/stem.erl
Compiled src/random_get.erl
Compiled src/ids.erl
Compiled src/leaf.erl
Compiled src/test_trie.erl
Compiled src/get.erl
Compiled src/delete.erl
Compiled src/cfg.erl
Compiled src/garbage.erl
==> chalang (compile)

Compiled src/disassembler.erl
Compiled src/test_chalang.erl
Compiled src/fractions.erl
/home/ubuntu/testnet/deps/chalang/src/compiler_lisp.erl:147: Warning: function print_binary/1 is unused
/home/ubuntu/testnet/deps/chalang/src/compiler_lisp.erl:351: Warning: function encode/1 is unused
Compiled src/compiler_lisp.erl
/home/ubuntu/testnet/deps/chalang/src/compiler_lisp2.erl:63: Warning: function quote_list/1 is unused
/home/ubuntu/testnet/deps/chalang/src/compiler_lisp2.erl:71: Warning: function quote_list2/1 is unused
/home/ubuntu/testnet/deps/chalang/src/compiler_lisp2.erl:247: Warning: function print_binary/1 is unused
/home/ubuntu/testnet/deps/chalang/src/compiler_lisp2.erl:256: Warning: function split/2 is unused
/home/ubuntu/testnet/deps/chalang/src/compiler_lisp2.erl:257: Warning: function split/3 is unused
/home/ubuntu/testnet/deps/chalang/src/compiler_lisp2.erl:462: Warning: function encode/1 is unused
Compiled src/compiler_lisp2.erl
....
ompiled src/compiler_chalang.erl
Compiled src/arithmetic_chalang.erl
/home/ubuntu/testnet/deps/chalang/src/chalang.erl:478: Warning: variable 'D' is unused
/home/ubuntu/testnet/deps/chalang/src/chalang.erl:481: Warning: no clause will ever match
Compiled src/chalang.erl
==> jiffy (compile)
Compiled src/jiffy_utf8.erl
Compiled src/jiffy.erl
Compiling c_src/decoder.c
....
==> testnet (compile)
src/test_key.erl:5: Warning: variable 'NewAddr' is unused
src/test_key.erl:5: Warning: variable 'NewPriv' is unused
src/test_key.erl:5: Warning: variable 'NewPub' is unused
Compiled src/test_key.erl
Compiled src/oracle_questions.erl
Compiled src/timing_experiment.erl
Compiled src/networking/serve.erl
Compiled src/networking/talker.erl
Compiled src/networking/request_frequency.erl
Compiled src/networking/port.erl
Compiled src/networking/main_handler.erl
Compiled src/networking/peers.erl
Compiled src/networking/internal_handler.erl
Compiled src/networking/external_handler.erl
Compiled src/market.erl
Compiled src/networking/handler.erl
Compiled src/inbox.erl
Compiled src/mail.erl
Compiled src/gas_price.erl
Compiled src/free_constants.erl
Compiled src/dice.erl
Compiled src/consensus/txs/txs.erl
src/consensus/txs/testnet_sign.erl:189: Warning: the guard for this clause evaluates to 'false'
Compiled src/consensus/txs/testnet_sign.erl
....
Compiled src/consensus/txs/new_channel_tx.erl
src/consensus/txs/test_txs.erl:346: Warning: a term is constructed, but never used
src/consensus/txs/test_txs.erl:734: Warning: variable 'PH' is unused
Compiled src/consensus/txs/test_txs.erl
Compiled src/consensus/txs/existence_tx.erl
Compiled src/consensus/txs/oracle_bet_tx.erl
Compiled src/consensus/txs/grow_channel_tx.erl
Compiled src/consensus/txs/delete_account_tx.erl
Compiled src/consensus/txs/create_account_tx.erl
Compiled src/consensus/txs/channel_timeout_tx.erl
Compiled src/consensus/txs/channel_team_close_tx.erl
Compiled src/consensus/txs/channel_solo_close.erl
Compiled src/consensus/txs/channel_slash_tx.erl
Compiled src/consensus/txs/channel_repo_tx.erl
Compiled src/consensus/tx_pool_feeder.erl
Compiled src/consensus/trees/tree_test.erl
Compiled src/consensus/tx_pool.erl
Compiled src/consensus/trees/trees.erl
Compiled src/consensus/trees/shares.erl
src/consensus/trees/orders.erl:217: Warning: a term is constructed, but never used
Compiled src/consensus/trees/orders.erl
...
Compiled src/consensus/testnet_hasher.erl
Compiled src/consensus/testnet_app.erl
Compiled src/consensus/trees/accounts.erl
Compiled src/consensus/tester.erl
Compiled src/consensus/sync.erl
Compiled src/consensus/packer.erl
src/consensus/secrets.erl:51: Warning: function old_new_lightning/0 is unused
src/consensus/secrets.erl:57: Warning: function test_new_lightning/0 is unused
Compiled src/consensus/secrets.erl
Compiled src/consensus/mine.erl
Compiled src/consensus/fractions.erl
Compiled src/consensus/keys.erl
src/consensus/download_blocks.erl:41: Warning: variable 'DBB' is unused
Compiled src/consensus/download_blocks.erl
Compiled src/consensus/chain/top.erl
Compiled src/consensus/chain/block_hashes.erl

Estoy usando el Bash de Ubuntu en Windows 10.

**Comment by Leonyxtested** [comment]
Mas de lo mismo, en este caso hay menos funciones que no se usan:

Compiled src/free_constants.erl
Compiled src/networking/handler.erl
Compiled src/easy.erl
src/consensus/txs/testnet_sign.erl:22: Warning: function to_bytes/1 is unused
src/consensus/txs/testnet_sign.erl:189: Warning: the guard for this clause evaluates to 'false'
Compiled src/consensus/txs/testnet_sign.erl
Compiled src/consensus/txs/spk.erl
Compiled src/consensus/tx_pool_feeder.erl
src/consensus/trees/trees.erl:60: Warning: variable 'N' is unused
Compiled src/consensus/trees/trees.erl
Compiled src/consensus/testnet_sup.erl
src/consensus/txs/test_txs.erl:347: Warning: a term is constructed, but never used
src/consensus/txs/test_txs.erl:735: Warning: variable 'PH' is unused
Compiled src/consensus/txs/test_txs.erl
Compiled src/consensus/tester.erl
Compiled src/consensus/chain/block_absorber.erl
src/consensus/download_blocks.erl:65: Warning: function get_blocks/5 is unused
Compiled src/consensus/download_blocks.erl
Compiled src/consensus/constants.erl
src/channels/secrets.erl:51: Warning: function old_new_lightning/0 is unused
src/channels/secrets.erl:57: Warning: function test_new_lightning/0 is unused
Compiled src/channels/secrets.erl
src/channels/order_book.erl:13: Warning: function make_order/4 is unused
src/channels/order_book.erl:74: Warning: variable 'E' is unused
Compiled src/channels/order_book.erl
Compiled src/channels/market.erl
Compiled src/consensus/chain/block.erl
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> start keys
start toptx pool started
starting secretsstart server
gensis maker accounts write
sync:start().
ok
2> top of sync
absorb block: 1
mine:start().
start mining with 2 cores.
top of sync
mine blocks
ok
3> top of sync
mine blocks
mine blocks
mine blocks

**Comment by zack-bitcoin** [comment]
It is true, there is some unused code which should be deleted.
The entire fractions library for example.

There are some places where I used if-statements like comments, which causes warnings.

**Comment by sennui** [comment]
this is under refactoring in specific tickets
