### ISSUE TITLE
Algunos errores

### ISSUE THREAD

**Issue by Leonyxtested** [aeternity/testnet#108]
Lo he reinstalado varias veces,lo curioso es que ayer iba bien. Por cierto,me gusta que cuando se inicia el minero tambien sincronice. Por cierto,estoy usando el Bash de Ubuntu 16.04.02 en Windows 10 Creator Update.

Solo sincronizar:

Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> start keys
start toptx pool started
starting secretsstart server
gensis maker accounts write
sync:start().
ok
2> top of sync
top returneddownloading blocks

=ERROR REPORT==== 8-Jun-2017::18:31:13 ===
Error in process <0.397.0> with exit value:
{{badmatch,false},
 [{block,check1,1,[{file,"src/consensus/chain/block.erl"},{line,270}]},
  {download_blocks,trade_blocks,4,
                   [{file,"src/consensus/download_blocks.erl"},{line,87}]},
  {download_blocks,'-sync/3-fun-1-',4,
                   [{file,"src/consensus/download_blocks.erl"},{line,47}]}]}
top of sync
top returneddownloading blocks

=ERROR REPORT==== 8-Jun-2017::18:32:15 ===
Error in process <0.404.0> with exit value:
{{badmatch,false},
 [{block,check1,1,[{file,"src/consensus/chain/block.erl"},{line,270}]},
  {download_blocks,trade_blocks,4,
                   [{file,"src/consensus/download_blocks.erl"},{line,87}]},
  {download_blocks,'-sync/3-fun-1-',4,
                   [{file,"src/consensus/download_blocks.erl"},{line,47}]}]}
top of sync
top returneddownloading blocks

=ERROR REPORT==== 8-Jun-2017::18:33:16 ===
Error in process <0.407.0> with exit value:
{{badmatch,false},
 [{block,check1,1,[{file,"src/consensus/chain/block.erl"},{line,270}]},
  {download_blocks,trade_blocks,4,
                   [{file,"src/consensus/download_blocks.erl"},{line,87}]},
  {download_blocks,'-sync/3-fun-1-',4,
                   [{file,"src/consensus/download_blocks.erl"},{line,47}]}]}
2> sync:stop().
ok

Cuando empieza el minado:

3> mine:start().
start mining with 2 cores.
top of sync
top returnedok
4> downloading blocks

=ERROR REPORT==== 8-Jun-2017::18:38:54 ===
Error in process <0.414.0> with exit value:
{{badmatch,false},
 [{block,check1,1,[{file,"src/consensus/chain/block.erl"},{line,270}]},
  {download_blocks,trade_blocks,4,
                   [{file,"src/consensus/download_blocks.erl"},{line,87}]},
  {download_blocks,'-sync/3-fun-1-',4,
                   [{file,"src/consensus/download_blocks.erl"},{line,47}]}]}
died!
=ERROR REPORT==== 8-Jun-2017::18:39:11 ===
** Generic server block_absorber terminating
** Last message in was {'$gen_cast',garbage}
** When Server state == []
** Reason for termination ==
** {{badrecord,block_plus},
    [{block,trees,1,[{file,"src/consensus/chain/block.erl"},{line,62}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,54}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,56}]},
     {trees,garbage,1,[{file,"src/consensus/trees/trees.erl"},{line,58}]},
     {trees,garbage,0,[{file,"src/consensus/trees/trees.erl"},{line,62}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,16}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]}]}
died!
=ERROR REPORT==== 8-Jun-2017::18:39:29 ===
** Generic server block_absorber terminating
** Last message in was {'$gen_cast',garbage}
** When Server state == []
** Reason for termination ==
** {{badrecord,block_plus},
    [{block,trees,1,[{file,"src/consensus/chain/block.erl"},{line,62}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,54}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,56}]},
     {trees,garbage,1,[{file,"src/consensus/trees/trees.erl"},{line,58}]},
     {trees,garbage,0,[{file,"src/consensus/trees/trees.erl"},{line,62}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,16}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]}]}
died!
=ERROR REPORT==== 8-Jun-2017::18:39:47 ===
** Generic server block_absorber terminating
** Last message in was {'$gen_cast',garbage}
** When Server state == []
** Reason for termination ==
** {{badrecord,block_plus},
    [{block,trees,1,[{file,"src/consensus/chain/block.erl"},{line,62}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,54}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,56}]},
     {trees,garbage,1,[{file,"src/consensus/trees/trees.erl"},{line,58}]},
     {trees,garbage,0,[{file,"src/consensus/trees/trees.erl"},{line,62}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,16}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]}]}
died!
=ERROR REPORT==== 8-Jun-2017::18:40:03 ===
** Generic server block_absorber terminating
** Last message in was {'$gen_cast',garbage}
** When Server state == []
** Reason for termination ==
** {{badrecord,block_plus},
    [{block,trees,1,[{file,"src/consensus/chain/block.erl"},{line,62}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,54}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,56}]},
     {trees,garbage,1,[{file,"src/consensus/trees/trees.erl"},{line,58}]},
     {trees,garbage,0,[{file,"src/consensus/trees/trees.erl"},{line,62}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,16}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]}]}
4> mine:stop().
ok
5> top of sync
top returneddownloading blocks

=ERROR REPORT==== 8-Jun-2017::18:40:13 ===
Error in process <0.434.0> with exit value:
{{badmatch,false},
 [{block,check1,1,[{file,"src/consensus/chain/block.erl"},{line,270}]},
  {download_blocks,trade_blocks,4,
                   [{file,"src/consensus/download_blocks.erl"},{line,87}]},
  {download_blocks,'-sync/3-fun-1-',4,
                   [{file,"src/consensus/download_blocks.erl"},{line,47}]}]}
5> sync:stop().
ok
6> died!
=ERROR REPORT==== 8-Jun-2017::18:40:20 ===
** Generic server block_absorber terminating
** Last message in was {'$gen_cast',garbage}
** When Server state == []
** Reason for termination ==
** {{badrecord,block_plus},
    [{block,trees,1,[{file,"src/consensus/chain/block.erl"},{line,62}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,54}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,56}]},
     {trees,garbage,1,[{file,"src/consensus/trees/trees.erl"},{line,58}]},
     {trees,garbage,0,[{file,"src/consensus/trees/trees.erl"},{line,62}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,16}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]}]}
6> sync:stop().
ok
7> mine:stop().
ok
8> mine:status().
stop
9> sync:status().
stop

**Comment by wilsonk** [comment]
I am running into this same problem today...same error messages. Just thought I would let you know @Leonyxtested wasn't alone in this. Ubuntu 15.04.

**Comment by Leonyxtested** [comment]
Gracias,dejame decirte que necesitas Ubuntu 16.04 o superior para que funcione bien,los repositorios de Erlang no se actualizan bien hasta esa versiòn @wilsonk ,otra cosa que te digo y se me a olvidado poner es que yo lo estoy haciendo funcionar en Windows 10, pienso que no es problema de @zack-bitcoin ,el lo esta haciendo bien,pienso que es mas de Microsoft que no esta dando un buen soporte a las traducciones. Lo extraño es que al pricipio funcionaba correctamente y al dia siguiente todo mal.

**Comment by wilsonk** [comment]
@Leonyxtested,  I updated to 16.04 now. I had manually installed recent versions of erl, etc. on my Ubuntu 15.04 install before, but I guess updating to 16.04 is probably best, if only to make sure things were really up to date and set up properly. I updated my testnet and restarted.

I am still getting some errors like "generic server block_absorber terminating" but I am not getting the same errors as you listed above anymore. I think things actually worked for my first run as I mined a few blocks! I could see 100% cpu usage and my balance was non-zero, yay! ...but then every time I tried afterwards I kept getting "generic server accounts_main terminating" and no cpu usage/no blocks found :(

I have tried dozens of times (sync'ed or non-sync'ed, etc.) and I just can't seem to get mining again. Not sure what is going on.

**Comment by Leonyxtested** [comment]
La verdad es que yo tampoco @wilsonk , a veces  esta el programador en Slack,pero hace mucho que no entro. Habra que esperar y actualizar hasta que funcione.

Usas una instalación de Ubuntu normal,no?

**Comment by wilsonk** [comment]
@Leonyxtested: I Updated today (Monday June 12) and things seem to work fine now. Yes, I use a normal Ubuntu install.

**Comment by Leonyxtested** [comment]
Si? Que suerte, a mi me salta mas errores:

Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> start keys
start toptx pool started
starting secretsstart server
gensis maker accounts write
sync:start().
ok
2> top of sync
top returned ["ok",["block_plus",["block",1,"7wfalvzzKjJ8SIsi",[-6],"Vh+Pjkkcy9DjdBma",1,146319435,6452,"",3],["pow","liyh2NsLkCHrK6t6",6177,734221742761315240381758],["trees",1,0,0,0,0,72],40370176,["7wfalvzzKjJ8SIsi"]],1]
downloading blocks
trade blockstop of sync
top returned ["ok",["block_plus",["block",1,"7wfalvzzKjJ8SIsi",[-6],"Vh+Pjkkcy9DjdBma",1,146319435,6452,"",3],["pow","liyh2NsLkCHrK6t6",6177,734221742761315240381758],["trees",1,0,0,0,0,72],40370176,["7wfalvzzKjJ8SIsi"]],1]
downloading blocks
trade blockstop of sync
top returned ["ok",["block_plus",["block",1,"7wfalvzzKjJ8SIsi",[-6],"Vh+Pjkkcy9DjdBma",1,146319435,6452,"",3],["pow","liyh2NsLkCHrK6t6",6177,734221742761315240381758],["trees",1,0,0,0,0,72],40370176,["7wfalvzzKjJ8SIsi"]],1]
downloading blocks
trade blo2> mine:start().
start mining with 2 cores.
top of sync
top returned ["ok",["block_plus",["block",1,"7wfalvzzKjJ8SIsi",[-6],"Vh+Pjkkcy9DjdBma",1,146319435,6452,"",3],["pow","liyh2NsLkCHrK6t6",6177,734221742761315240381758],["trees",1,0,0,0,0,72],40370176,["7wfalvzzKjJ8SIsi"]],1]
downloading blocks
trade blocksok
3> mine:start().died!
=ERROR REPORT==== 12-Jun-2017::18:57:59 ===
** Generic server block_absorber terminating
** Last message in was {'$gen_cast',garbage}
** When Server state == []
** Reason for termination ==
** {{badrecord,block_plus},
    [{block,trees,1,[{file,"src/consensus/chain/block.erl"},{line,62}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,54}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,56}]},
     {trees,garbage,1,[{file,"src/consensus/trees/trees.erl"},{line,58}]},
     {trees,garbage,0,[{file,"src/consensus/trees/trees.erl"},{line,62}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,16}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]}]}
3> sync:stop().
ok
4> mine:stop().
ok
5> died!
=ERROR REPORT==== 12-Jun-2017::18:58:16 ===
** Generic server block_absorber terminating
** Last message in was {'$gen_cast',garbage}
** When Server state == []
** Reason for termination ==
** {{badrecord,block_plus},
    [{block,trees,1,[{file,"src/consensus/chain/block.erl"},{line,62}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,54}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,56}]},
     {trees,garbage,1,[{file,"src/consensus/trees/trees.erl"},{line,58}]},
     {trees,garbage,0,[{file,"src/consensus/trees/trees.erl"},{line,62}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,16}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]}]}

**Comment by wilsonk** [comment]
@Leonyxtested I was getting that type of error on Saturday, but once I did a 'git pull' and 'sh clean.sh' before a new 'sh start.sh' things seem to be working. I may have also done an 'sh update.sh' but I don't think that is necessary in this case. 

Hopefully things work out for you with a new pull and clean!

**Comment by Leonyxtested** [comment]
Vaya! Habia visto lo de ´git pull´ pero no sabia a que se referia,lo que puesto,se actualizado de alguna manera y ahora parece que va bien,salvo por las funciones que no usa:

Compiled src/free_constants.erl
Compiled src/networking/handler.erl
Compiled src/easy.erl
src/consensus/txs/testnet_sign.erl:22: Warning: function to_bytes/1 is unused
src/consensus/txs/testnet_sign.erl:189: Warning: the guard for this clause evaluates to 'false'
Compiled src/consensus/txs/testnet_sign.erl
Compiled src/consensus/txs/spk.erl
Compiled src/consensus/tx_pool_feeder.erl
src/consensus/trees/trees.erl:60: Warning: variable 'N' is unused
Compiled src/consensus/trees/trees.erl
Compiled src/consensus/testnet_sup.erl
src/consensus/txs/test_txs.erl:347: Warning: a term is constructed, but never used
src/consensus/txs/test_txs.erl:735: Warning: variable 'PH' is unused
Compiled src/consensus/txs/test_txs.erl
Compiled src/consensus/tester.erl
Compiled src/consensus/chain/block_absorber.erl
src/consensus/download_blocks.erl:65: Warning: function get_blocks/5 is unused
Compiled src/consensus/download_blocks.erl
Compiled src/consensus/constants.erl
src/channels/secrets.erl:51: Warning: function old_new_lightning/0 is unused
src/channels/secrets.erl:57: Warning: function test_new_lightning/0 is unused
Compiled src/channels/secrets.erl
src/channels/order_book.erl:13: Warning: function make_order/4 is unused
src/channels/order_book.erl:74: Warning: variable 'E' is unused
Compiled src/channels/order_book.erl
Compiled src/channels/market.erl
Compiled src/consensus/chain/block.erl
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> start keys
start toptx pool started
starting secretsstart server
gensis maker accounts write
sync:start().
ok
2> top of sync
absorb block: 1
mine:start().
start mining with 2 cores.
top of sync
mine blocks
ok
3> top of sync
mine blocks
mine blocks
mine blocks

**Comment by wilsonk** [comment]
@Leonyxtested  Sounds good, glad it works for you now. I get similar warnings about unused variables, but that isn't a big deal.

**Comment by zack-bitcoin** [comment]
It looks like @wilsonk solved this problem. Thank you.
The code is changing frequently, so if something doesn't work, it usually means you need to download the new version.
