### ISSUE TITLE
Initial clone build/install issue.

### ISSUE THREAD

**Issue by rkazak** [aeternity/testnet#109]
Hi,
Just cloned the testnet repository. I am on a mac and followed the info in
compile_mac.md -
git clone https://github.com/aeternity/testnet.git
cd testnet
mkdir data blocks  ( BTW this is already done in the clean.sh? )
sh install.sh

Now running these steps in a brand new environment results in the following;
+ sh clean.sh
cp: keys_backup: No such file or directory

From the log of the file clean.sh I would suggest we don't account for
a 'fresh' install.
macbook:testnet rkazak$ sh -x ./clean.sh 
+ '[' -e data/keys.db ']'
+ rm -r data
+ mkdir data
+ rm -r blocks
+ mkdir blocks
+ '[' -d backup ']'
+ touch backup/temp.db
+ rm backup/temp.db
+ cp keys_backup data/keys.db
cp: keys_backup: No such file or directory

So my other question is how do we initially generate the 'keys.db'?

**Comment by zack-bitcoin** [comment]
the keys_backup error can be safely ignored. Thank you for pointing this out.
You can create a new private key using `keys:new("CHANGE_THIS_PASSWORD").`
When you create a new private key, it overwrites the keys.db file with a new keys.db file.
