### ISSUE TITLE
 update.sh: ./rebar: not found

### ISSUE THREAD

**Issue by bilbma** [aeternity/testnet#115]
64 ubuntu 14.04
ae@ae-VirtualBox:~$ cd testnet/
ae@ae-VirtualBox:~/testnet$ sh update.sh
remote: Counting objects: 818, done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 818 (delta 372), reused 376 (delta 351), pack-reused 415
Receiving objects: 100% (818/818), 1.66 MiB | 1.02 MiB/s, done.
Resolving deltas: 100% (630/630), completed with 84 local objects.
De https://github.com/aeternity/testnet
 * branch            master     -> FETCH_HEAD
   2c6f82a..21867b5  master     -> origin/master
Updating 2c6f82a..21867b5
Fast-forward
 LICENSE.md                                   |  14 +
 README.md                                    |  20 +-
 backup/README.md                             |   2 +
 backup/experimental.tar.bz2                  | Bin 0 -> 884959 bytes
 backup/plasmodial.tar.bz2                    | Bin 0 -> 624625 bytes
 blocks/save/ignore                           |   2 -
 clean.sh                                     |  11 +-
 data/backup_data/ignore                      |   2 -
 dev1_mode.sh                                 |   4 +
 dev2_mode.sh                                 |  17 +
 dev3_mode.sh                                 |  17 +
 docs/accounts_channels.md                    |   4 +-
 docs/batch_channel.png                       | Bin 0 -> 3609 bytes
 docs/batch_channel_unbalanced.png            | Bin 0 -> 3621 bytes
 docs/channels.md                             |   2 +
 docs/commands.md                             |  28 ++
 docs/commands_accounts.md                    |  42 ++
 docs/commands_basics.md                      |  30 ++
 docs/commands_channels.md                    |  32 ++
 docs/commands_mining.md                      |  15 +
 docs/commands_oracle.md                      |  46 ++
 docs/commands_other.md                       |  18 +
 docs/compile_mac.md                          |  17 +-
 docs/contributions.md                        |   2 +-
 docs/dapp_developer_introduction.md          |  28 +-
 docs/dominant_assurance_contract.md          |   4 +-
 docs/faq.md                                  |  17 +
 docs/financial_options.md                    |   4 +
 docs/flat_hierarchy.md                       |  16 +
 docs/how_to_use_channels.md                  |  39 ++
 docs/off_line_limit_order_channel.md         |  56 +++
 docs/options.md                              |   4 +
 docs/oracle.md                               |  17 +-
 docs/oracle_answers_for_smith_crown.md       |  11 +-
 docs/oracle_design.md                        |  60 ---
 docs/oracle_lifecycle.md                     |   3 -
 docs/oracle_motivations.md                   |   5 +-
 docs/oracle_off_chain.md                     |  28 --
 docs/oracle_order_book.md                    |  50 ---
 docs/raising_funds.md                        |  16 +
 docs/running_tests.md                        |  11 +
 docs/stablecoin.md                           |   3 +
 docs/test_mode.md                            |  28 ++
 docs/todo.md                                 |  84 ++--
 docs/town_crier.md                           |   5 +-
 docs/transaction_types.md                    |   3 +
 docs/trustless_markets.md                    |  11 +
 docs/warning.md                              |  18 +
 install.sh                                   |  38 +-
 lightning_test.sh                            |  46 --
 rebar.config                                 |   2 +-
 setup_test.sh                                |   6 +
 src/channels/arbitrage.erl                   | 188 ++------
 src/channels/arbitrage_old.erl               | 158 +++++++
 src/channels/channel_feeder.erl              | 294 ++++++-------
 src/channels/channel_manager.erl             |   1 +
 src/channels/market.erl                      | 181 ++++++++
 src/channels/market.fs                       | 100 +++++
 src/channels/oracle_bet.fs                   |  46 ++
 src/channels/order_book.erl                  | 173 ++++++++
 src/channels/secrets.erl                     |  99 +++++
 src/consensus/chain/block.erl                | 244 +++++++----
 src/consensus/chain/block_absorber.erl       |  29 +-
 src/consensus/chain/block_hashes.erl         |   2 +-
 src/consensus/constants.erl                  |  27 +-
 src/consensus/download_blocks.erl            |  58 ++-
 src/consensus/keys.erl                       |  31 +-
 src/consensus/mine.erl                       |  23 +-
 src/consensus/sync.erl                       |  56 +++
 src/consensus/tester.erl                     |   6 +
 src/consensus/testnet_app.erl                |   1 +
 src/consensus/testnet_sup.erl                |  11 +-
 .../trees/{account.erl => accounts.erl}      |  15 +-
 src/consensus/trees/burn.erl                 |   3 +-
 .../trees/{channel.erl => channels.erl}      |   4 +-
 src/consensus/trees/existence.erl            |   4 +-
 src/consensus/trees/governance.erl           |  59 ++-
 src/consensus/trees/oracles.erl              |   2 +-
 src/consensus/trees/tree_test.erl            |   4 +-
 src/consensus/trees/trees.erl                |  41 +-
 src/consensus/tx_pool_feeder.erl             |  46 +-
 src/consensus/txs/channel_repo_tx.erl        |  20 +-
 src/consensus/txs/channel_slash_tx.erl       |  51 ++-
 src/consensus/txs/channel_solo_close.erl     | 141 ++----
 src/consensus/txs/channel_team_close_tx.erl  |  40 +-
 src/consensus/txs/channel_timeout_tx.erl     |  68 +--
 src/consensus/txs/create_account_tx.erl      |  20 +-
 src/consensus/txs/delete_account_tx.erl      |  18 +-
 src/consensus/txs/existence_tx.erl           |   8 +-
 src/consensus/txs/grow_channel_tx.erl        |  44 +-
 src/consensus/txs/new_channel_tx.erl         |  35 +-
 src/consensus/txs/oracle_bet_tx.erl          |  30 +-
 src/consensus/txs/oracle_close_tx.erl        |  26 +-
 src/consensus/txs/oracle_new_tx.erl          |   8 +-
 src/consensus/txs/oracle_shares_tx.erl       |  16 +-
 src/consensus/txs/oracle_unmatched_tx.erl    |   8 +-
 src/consensus/txs/repo_tx.erl                |  18 +-
 src/consensus/txs/spend_tx.erl               |  18 +-
 src/consensus/txs/spk.erl                    | 310 +++++++++++--
 src/consensus/txs/test_txs.erl               | 331 ++++++++++----
 src/consensus/txs/testnet_sign.erl           |  40 +-
 src/consensus/txs/txs.erl                    |   6 +-
 src/dice.erl                                 |  39 +-
 src/easy.erl                                 | 387 ++++++++++++++---
 src/free_constants.erl                       |  24 +-
 src/networking/handler.erl                   | 112 +++--
 src/networking/internal_handler.erl          | 128 +-----
 src/networking/peers.erl                     |   5 +-
 src/networking/request_frequency.erl         |  35 ++
 src/networking/serve.erl                     |   2 +-
 src/networking/talker.erl                    |  22 +-
 src/secrets.erl                              |   6 -
 start.sh                                     |   6 +-
 tests/channel_test.sh                        |  35 +-
 tests/header_test.sh                         |   3 +
 tests/lightning_test.sh                      |  61 +++
 tests/server_check.sh                        |   1 +
 tests/share_blocks_test.sh                   |  13 +-
 update.sh                                    |  13 +-
 119 files changed, 3489 insertions(+), 1503 deletions(-)
 create mode 100644 LICENSE.md
 create mode 100644 backup/README.md
 create mode 100644 backup/experimental.tar.bz2
 create mode 100644 backup/plasmodial.tar.bz2
 delete mode 100644 blocks/save/ignore
 delete mode 100644 data/backup_data/ignore
 create mode 100644 dev1_mode.sh
 create mode 100644 dev2_mode.sh
 create mode 100644 dev3_mode.sh
 create mode 100644 docs/batch_channel.png
 create mode 100644 docs/batch_channel_unbalanced.png
 create mode 100644 docs/commands.md
 create mode 100644 docs/commands_accounts.md
 create mode 100644 docs/commands_basics.md
 create mode 100644 docs/commands_channels.md
 create mode 100644 docs/commands_mining.md
 create mode 100644 docs/commands_oracle.md
 create mode 100644 docs/commands_other.md
 create mode 100644 docs/faq.md
 create mode 100644 docs/financial_options.md
 create mode 100644 docs/flat_hierarchy.md
 create mode 100644 docs/how_to_use_channels.md
 create mode 100644 docs/off_line_limit_order_channel.md
 create mode 100644 docs/options.md
 delete mode 100644 docs/oracle_design.md
 delete mode 100644 docs/oracle_lifecycle.md
 delete mode 100644 docs/oracle_off_chain.md
 delete mode 100644 docs/oracle_order_book.md
 create mode 100644 docs/raising_funds.md
 create mode 100644 docs/running_tests.md
 create mode 100644 docs/stablecoin.md
 create mode 100644 docs/test_mode.md
 create mode 100644 docs/trustless_markets.md
 create mode 100644 docs/warning.md
 delete mode 100644 lightning_test.sh
 create mode 100644 setup_test.sh
 create mode 100644 src/channels/arbitrage_old.erl
 create mode 100644 src/channels/market.erl
 create mode 100644 src/channels/market.fs
 create mode 100644 src/channels/oracle_bet.fs
 create mode 100644 src/channels/order_book.erl
 create mode 100644 src/channels/secrets.erl
 create mode 100644 src/consensus/sync.erl
 rename src/consensus/trees/{account.erl => accounts.erl} (94%)
 rename src/consensus/trees/{channel.erl => channels.erl} (99%)
 create mode 100644 src/networking/request_frequency.erl
 delete mode 100644 src/secrets.erl
 create mode 100644 tests/lightning_test.sh
 create mode 100644 tests/server_check.sh
update.sh: 4: update.sh: ./rebar: not found
update.sh: 5: update.sh: ./rebar: not found
ae@ae-VirtualBox:~/testnet$ sh start.sh
update.sh: 2: update.sh: ./rebar: not found
update.sh: 3: update.sh: ./rebar: not found
Erlang R16B03 (erts-5.10.4) [source] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V5.10.4  (abort with ^G)
1> {"init terminating in do_boot",{undef,[{serve,pw,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,569}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,118}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
ae@ae-VirtualBox:~/testnet$ sh clean.sh
rm: no se puede borrar «data»: No existe el archivo o el directorio
rm: no se puede borrar «blocks»: No existe el archivo o el directorio
cp: no se puede efectuar `stat' sobre «keys_backup»: No existe el archivo o el directorio
ae@ae-VirtualBox:~/testnet$ sh start.sh
update.sh: 2: update.sh: ./rebar: not found
update.sh: 3: update.sh: ./rebar: not found
Erlang R16B03 (erts-5.10.4) [source] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V5.10.4  (abort with ^G)
1> {"init terminating in do_boot",{undef,[{serve,pw,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,569}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,118}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
ae@ae-VirtualBox:~/testnet$ sh start 3666
sh: 0: Can't open start
ae@ae-VirtualBox:~/testnet$ ./rebar get-deps
bash: ./rebar: No existe el archivo o el directorio
ae@ae-VirtualBox:~/testnet$ cd update.sh
bash: cd: update.sh: No es un directorio
ae@ae-VirtualBox:~/testnet$ ./rebar get-deps
bash: ./rebar: No existe el archivo o el directorio
ae@ae-VirtualBox:~/testnet$ cd ~
ae@ae-VirtualBox:~$ ./rebar get-deps
==> ae (get-deps)
ae@ae-VirtualBox:~$ cd update.sh
bash: cd: update.sh: No existe el archivo o el directorio
ae@ae-VirtualBox:~$ ./rebar compile
==> ae (compile)
ae@ae-VirtualBox:~$ sudo apt-get install erlang libncurses5-dev libssl-dev unixodbc-dev g++ git erlang-base-hipe
[sudo] password for ae: 
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
g++ ya está en su versión más reciente.
libncurses5-dev ya está en su versión más reciente.
unixodbc-dev ya está en su versión más reciente.
git ya está en su versión más reciente.
libssl-dev ya está en su versión más reciente.
erlang ya está en su versión más reciente.
erlang-base-hipe ya está en su versión más reciente.
0 actualizados, 0 se instalarán, 0 para eliminar y 0 no actualizados.
ae@ae-VirtualBox:~$ sh start 3666
sh: 0: Can't open start
ae@ae-VirtualBox:~$ sh update.sh
sh: 0: Can't open update.sh
ae@ae-VirtualBox:~$ cd testnet
ae@ae-VirtualBox:~/testnet$ sh update.sh
update.sh: 2: update.sh: ./rebar: not found
update.sh: 3: update.sh: ./rebar: not found
ae@ae-VirtualBox:~/testnet$ ./rebar get-deps
bash: ./rebar: No existe el archivo o el directorio
ae@ae-VirtualBox:~/testnet$ sh update.sh

ae@ae-VirtualBox:~/testnet$ sh install.sh
--2017-06-19 13:06:17--  https://raw.githubusercontent.com/wiki/rebar/rebar/rebar
Resolviendo raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.132.133
Conectando con raw.githubusercontent.com (raw.githubusercontent.com)[151.101.132.133]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 207979 (203K) [application/octet-stream]
Grabando a: “rebar”

100%[=====================================================================================>] 207.979     --.-K/s   en 0,1s    

2017-06-19 13:06:18 (2,05 MB/s) - “rebar” guardado [207979/207979]

==> testnet (get-deps)
Pulling trie from {git,"https://github.com/BumblebeeBat/MerkleTrie",
                       {tag,"master"}}
Clonar en «trie»...
Pulling chalang from {git,"https://github.com/zack-bitcoin/chalang",
                          {tag,"master"}}
Clonar en «chalang»...
Pulling jiffy from {git,"https://github.com/davisp/jiffy",{tag,"0.14.8"}}
Clonar en «jiffy»...
Pulling cowboy from {git,"https://github.com/ninenines/cowboy.git",
                         {tag,"1.0.4"}}
Clonar en «cowboy»...
==> trie (get-deps)
Pulling pink_hash from {git,"https://github.com/BumblebeeBat/pink_crypto",
                            {tag,"master"}}
Clonar en «pink_hash»...
*** Error in `git': free(): invalid pointer: 0x08c86f68 ***
error: unpack-objects died of signal 6
fatal: unpack-objects failed
ERROR: sh(git clone -n https://github.com/BumblebeeBat/pink_crypto pink_hash)
failed with return code 128 and the following output:
Clonar en «pink_hash»...
*** Error in `git': free(): invalid pointer: 0x08c86f68 ***
error: unpack-objects died of signal 6
fatal: unpack-objects failed

ERROR: 'get-deps' failed while processing /home/ae/testnet/deps/trie: rebar_abort
==> trie (compile)
Dependency not available: pink_hash-1 ({git,
                                        "https://github.com/BumblebeeBat/pink_crypto",
                                        {tag,"master"}})
Dependency not available: dump-1 ({git,
                                      "https://github.com/BumblebeeBat/dump",
                                      {tag,"master"}})
ERROR: compile failed while processing /home/ae/testnet/deps/trie: rebar_abort
cp: no se puede efectuar `stat' sobre «keys_backup»: No existe el archivo o el directorio
ae@ae-VirtualBox:~/testnet$ sh update.sh
==> trie (get-deps)
Pulling pink_hash from {git,"https://github.com/BumblebeeBat/pink_crypto",
                            {tag,"master"}}
Clonar en «pink_hash»...
Pulling dump from {git,"https://github.com/BumblebeeBat/dump",{tag,"master"}}
Clonar en «dump»...
==> pink_hash (get-deps)
Pulling encrypter from {git,"https://github.com/zack-bitcoin/encrypter",
                            {tag,"master"}}
Clonar en «encrypter»...
==> encrypter (get-deps)
==> dump (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowboy (get-deps)
Pulling cowlib from {git,"https://github.com/ninenines/cowlib.git","1.0.0"}
Clonar en «cowlib»...
Pulling ranch from {git,"https://github.com/ninenines/ranch.git","1.0.0"}
Clonar en «ranch»...
==> cowlib (get-deps)
==> ranch (get-deps)
==> testnet (get-deps)
==> encrypter (compile)
Compiled src/encrypter_app.erl
Compiled src/encrypter_sup.erl
Compiled src/sign.erl
Compiled src/encryption.erl
==> pink_hash (compile)
Compiled src/pink_hash_sup.erl
Compiled src/hash.erl
Compiled src/address.erl
Compiled src/pow.erl
Compiled src/pow_hash.erl
Compiled src/pink_hash_app.erl
Compiled src/sign.erl
Compiled src/elliptic.erl
==> dump (compile)
Compiled src/dump_ids.erl
Compiled src/test_dump.erl
Compiled src/bits.erl
Compiled src/dump.erl
Compiled src/dump_app.erl
Compiled src/dump_sup.erl
Compiled src/test_lists.erl
Compiled src/db.erl
Compiled src/file_manager.erl
==> trie (compile)
Compiled src/get.erl
Compiled src/random_get.erl
Compiled src/trie_sup.erl
Compiled src/trie.erl
Compiled src/verify.erl
Compiled src/store.erl
Compiled src/cfg.erl
Compiled src/garbage.erl
Compiled src/stem.erl
Compiled src/delete.erl
Compiled src/leaf.erl
Compiled src/trie_app.erl
Compiled src/test_trie.erl
Compiled src/ids.erl
==> chalang (compile)
Compiled src/chalang_sup.erl
Compiled src/fractions.erl
Compiled src/compiler_chalang.erl
Compiled src/disassembler.erl
Compiled src/test_chalang.erl
/home/ae/testnet/deps/chalang/src/compiler_lisp2.erl:63: Warning: function quote_list/1 is unused
/home/ae/testnet/deps/chalang/src/compiler_lisp2.erl:71: Warning: function quote_list2/1 is unused
/home/ae/testnet/deps/chalang/src/compiler_lisp2.erl:247: Warning: function print_binary/1 is unused
/home/ae/testnet/deps/chalang/src/compiler_lisp2.erl:256: Warning: function split/2 is unused
/home/ae/testnet/deps/chalang/src/compiler_lisp2.erl:257: Warning: function split/3 is unused
/home/ae/testnet/deps/chalang/src/compiler_lisp2.erl:462: Warning: function encode/1 is unused
Compiled src/compiler_lisp2.erl
Compiled src/chalang_app.erl
Compiled src/chalang_constants.erl
Compiled src/arithmetic_chalang.erl
/home/ae/testnet/deps/chalang/src/chalang.erl:92: syntax error before: '{'
/home/ae/testnet/deps/chalang/src/chalang.erl:110: syntax error before: '{'
/home/ae/testnet/deps/chalang/src/chalang.erl:2: function data_maker/7 undefined
/home/ae/testnet/deps/chalang/src/chalang.erl:2: function test/6 undefined
/home/ae/testnet/deps/chalang/src/chalang.erl:86: function test/6 undefined
/home/ae/testnet/deps/chalang/src/chalang.erl:80: Warning: function make_tuple/2 is unused
/home/ae/testnet/deps/chalang/src/chalang.erl:82: Warning: function make_list/3 is unused
/home/ae/testnet/deps/chalang/src/chalang.erl:478: Warning: variable 'D' is unused
Compiling /home/ae/testnet/deps/chalang/src/chalang.erl failed:
ERROR: compile failed while processing /home/ae/testnet/deps/chalang: rebar_abort
ae@ae-VirtualBox:~/testnet$

**Comment by zack-bitcoin** [comment]
to install rebar, do `sh install.sh`.
Look at the README for up to date information on how to install and run a node.
