### ISSUE TITLE
Ubuntu cant start mining or using (newbie)

### ISSUE THREAD

**Issue by rosoposo** [aeternity/testnet#116]
So i have followed the simple steps https://github.com/aeternity/testnet/blob/master/docs/compile_ubuntu.md and then 
sh install.sh gives finishes with 
rm: cannot remove 'data': No such file or directory
rm: cannot remove 'blocks': No such file or directory
cp: cannot stat 'keys_backup': No such file or directory

Then
sh start.sh
==> encrypter (get-deps)
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> encrypter (compile)
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> start keys
start toptx pool started
starting secretsstart server
gensis maker accounts write 

I cant seem to get any response from commands mine:status() and all that just responds without any results or return items

1> mine:status()
1> 

Any ideas on what I am doing wrong?

**Comment by zack-bitcoin** [comment]
erlang commands need a period at the end.
It is like prolog syntax.
`mine:status().`
`mine:start().`
`mine:stop().`

**Comment by webdigi** [comment]
Awesome thanks. that works now. Sorry to bother you!

**Comment by ByoundG** [comment]
Hi,

On Ubuntu 16, to try the testnet, i have follow : https://github.com/aeternity/testnet/blob/master/docs/getting-started/ubuntu_dependencies.md

But when i got to :  cd testnet
and try to run :  sh install.sh

The terminal answer : Can't open install.sh

Could you explain me what i have to do as the install.sh file do not appear on the repository,

Regards,

**Comment by cytadela8** [comment]
@ByoundG `sh install.sh` was removed a while ago. We have just reworked the instructions. Please try current version: https://github.com/aeternity/testnet/blob/master/docs/getting-started/linux_dependencies.md
After installing the dependencies here are the basic usage instructions: https://github.com/aeternity/testnet/blob/master/docs/getting-started/turn_it_on.md

**Comment by ByoundG** [comment]
On a fresh update, from ubuntu, erlang, github,
I did : 
make prod-attach // "that answer erlang.pip.1"
syn:start(). // "ok"
keys:new("SeaArt"). //"ok"

then :
keys:pubkeys(). // ** exception exit: {noproc,{gen_server,call,[keys,pubkey]}}
     in function  gen_server:call/2 (gen_server.erl, line 204)
or : 
keys:address(). // "** exception error: undefined function keys:address/0"

Would you tell me how to create a account on the prod nod,

Obligingly,

**Comment by sennui** [comment]
@ByoundG can you point me to the documentation that you are using? (it is not accurate)

1. we have now function:` keys:pubkey()` (no s at the end)
2. key-address. We removed int like addresses and use pub keys now instaed

Can you tell me what you want to achieve? Maybe I can help and tell you whats relevant doc (please use this directory as a source of truth https://github.com/aeternity/testnet/tree/master/docs )
