### ISSUE TITLE
Mac, start.sh hangs at "gensis maker accounts write"

### ISSUE THREAD

**Issue by mdix** [aeternity/testnet#125]
When pressing Enter, I get a prompt (1>) but entering stuff doesn't do anything. I waited for 15 minutes at "genesis maker accounts write" but nothing happened. Am I doing it wrong?

MacOS: 10.12.5
Erlang: Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace] Eshell V8.3  (abort with ^G)
Commit hash I tried to run on: 19f5842af6695ed31948ab564aa7d1376bccee95

Thanks for your help and best
Marc

**Comment by mdix** [comment]
Ok, got it working. Have to press Enter to get the prompt (would be nice if the tool would tell it to the user or show the prompt instead of pretending to actually do some work) and didn't know that erlang statements are terminated by a `.`. 

Suggestion: Update the program to either show the prompt directly or echo a message which tells the user that he can now press ENTER and enter commands?

**Comment by zack-bitcoin** [comment]
Yes, thank you for mentioning this.

**Comment by zack-bitcoin** [comment]
The new pull request we just got from Sennui should have fixed this problem.
