### ISSUE TITLE
backup keys

### ISSUE THREAD

**Issue by zack-bitcoin** [aeternity/testnet#13]
Right now every time you restart the node it deletes your private key.
We need it to automatically save your encrypted private key.

**Comment by stefek99** [comment]
:)

See: https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/issues/123

Thanks god it's not `rm -rf /usr`

**Comment by cytadela8** [comment]
It seams any change to keys is imminently saved on disk. See file [consensus/keys.erl](../blob/master/src/consensus/keys.erl)

**Comment by zack-bitcoin** [comment]
yes, this issues should be closed. Cytadela8 is right.
