### ISSUE TITLE
create account

### ISSUE THREAD

**Issue by zack-bitcoin** [aeternity/testnet#14]
It should automatically select an available ID for you. 
Don't make the user choose it.
Do the same for channel ids.

**Comment by cytadela8** [comment]
It seams keys ids are updated automatically. The update_id function is invoked by: consensus/txs/create_account_tx.erl and consensus/chain/block.erl (also consensus/chain/top.erl, but that isn't relevant).

**Comment by zack-bitcoin** [comment]
cytadela8 is right, this issue should be closed.
