### ISSUE TITLE
Poblemas en general

### ISSUE THREAD

**Issue by Leonyxtested** [aeternity/testnet#15]
El codigo parece bien pero estamos teniendo problemas a la hora de enviarnos los balances,las ID se repiten por lo que no deja enviar si son iguales,para crear una nueva cuenta no se sabe si se hara bien y no se explica muy bien todas las cosas. Estoy intentando estudiar el lenguaje para poder comprenderlo mejor.Gracias.

**Comment by zack-bitcoin** [comment]
#14 
este problema es el mismo en numero 14.
Vamos a arreglar temprano. Estoy ocupado ahora con la crowdsale.
