### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by zack-bitcoin** [aeternity/testnet#17]
Most things already have tests, but more tests would be helpful.
It is important to get rid of all the bugs.

**Comment by stefek99** [comment]
> It is important to get rid of all the bugs.

For me the main value of tests is to handle regressions - you made a seemingly unrelated change somewhere, and then out of the sudden...

**Comment by zack-bitcoin** [comment]
There are several. channel_test.sh, spend_test.sh, test.sh
Of course, we could always use more.

**Comment by Leonyxtested** [comment]
En esos tres se produce el fallo que intentan acceder a un servidor alojado en la misma maquina y no lo encuentran,añadir la IP del servidor Cowboy y su puerto podria ser una forma de probar si funcionan bien.

**Comment by stefek99** [comment]
@leonyxtested - are you on Slack / Telegram? I'd like to ask why do you commicate in Spanish? Most coders I know speak at least tiny bits of English...

**Comment by Leonyxtested** [comment]
Si,estoy en Telegram con el mismo nombre pero sin tested.

Te respondere rapido,yo leo mas o menos el ingles pero no se escribirlo bien,tengo que traducirlo,escibir en Español y traducirlo al Ingles es lo mismo que si usted lo traduce.

Espero que no ser muy molesto.

**Comment by stefek99** [comment]
![image](https://cloud.githubusercontent.com/assets/249703/24841488/fb3a4362-1d7d-11e7-9df0-455218814f8e.png)

It's OK, one way or another one of us has to translate... :)

**Comment by zack-bitcoin** [comment]
si queres usar channel_test.sh o los otros, primera necesitas leer.
https://github.com/aeternity/testnet/blob/master/channel_test.sh

There are comments in the file that explain how to run the test.

**Comment by zack-bitcoin** [comment]
I know some Spanish, and I want the Spanish speaking developers to feel welcome.
Hablo espannol. Quiero que el comunidad de developers espannoles pueden ayudarme.

**Comment by liuhongchao** [comment]
perhaps some unit tests with eunit?

**Comment by zack-bitcoin** [comment]
@liuhongchao /src/consensus/tester.erl has some tests.

**Comment by liuhongchao** [comment]
@zack-bitcoin Great! Will take a look. I m wondering what is the best way to get involved, one thought is that perhaps i can start with writing some unit tests. any suggestions on area to test or getting started in general?
