### ISSUE TITLE
install on to a mac

### ISSUE THREAD

**Issue by zack-bitcoin** [aeternity/testnet#18]
steps for installing erlang and aeternity testnet to a OSX computer

**Comment by stefek99** [comment]
Starting from...

> brew install erlang

My Ubuntu VM is painfully slow...

I'm so freakin' terrible at solving build problems but I'm hoping for the best, pretty sure you didn't use any esoteric libraries / dependencies.

**Comment by StrongLLC** [comment]
as long as you end the night without a piss jug, all is well

**Comment by zack-bitcoin** [comment]
I can't find the `./` you are refering to. I see a lot of `sh start.sh`

**Comment by stefek99** [comment]
Visual diff :)

On Mac no such thing as `./`

![image](https://cloud.githubusercontent.com/assets/249703/24827569/50681534-1c44-11e7-867d-9c28d36fefbf.png)

**Comment by zack-bitcoin** [comment]
I looked it up. OSX does have ./
That is how you execute files in the current directory.
It looks like this solution works for you because you already had rebar installed.
Many users will not have rebar installed, I don't think OSX has rebar installed by default.

I can't understand why start.sh wouldn't work for you if install.sh did.

Maybe you did the the `./rebar get` manually?
I don't have a mac to test this out on.

**Comment by stefek99** [comment]
Look a thing my first comment on this issue.

'brew install rebar'

That's how you install it.

Look at linked StackOverflow question - I'll apply their suggestion and submit pull request.

**Comment by zack-bitcoin** [comment]
Should we install rebar on all the systems instead of using the local directory?
I think every linux is a little different.
Simply installing to the local directory seems like it would work for everyone.
Rebar recommends installing using the command I put into install.sh

**Comment by stefek99** [comment]
`brew install rebar` - global install, adds to the PATH... _(not a local directory)_

**Comment by zack-bitcoin** [comment]
https://github.com/rebar/rebar/wiki/Getting-started

The official rebar repository recommends installing in the way I programmed. Not using brew or any package manager. Not installing to the system. Just the local directory.
I already wrote code to do this on mac. it is in install.sh

**Comment by zack-bitcoin** [comment]
I don't want to assume that the user already has brew installed. Most people don't.

**Comment by stefek99** [comment]
I never assumed user has brew installed.

https://github.com/aeternity/testnet/pull/29/files#diff-bf1b6d5bfe119bf7d3ecaf4dc0636334R46

> You should have https://brew.sh/ installed, that makes installing other packages easier.

![image](https://cloud.githubusercontent.com/assets/249703/24897922/b6bb1d40-1e92-11e7-9452-0194ac1ea543.png)

Top result suggest using `brew` https://gist.github.com/recr0ns/ba1d0f1dc859c9789a23

----

Why are we wasting energy here?

Next person with the Mac will step in and resolve the issue...

**Comment by zack-bitcoin** [comment]
I agree that using  brew to install erlang is a good method on Mac.
So we might as well also use it for rebar.

**Comment by zack-bitcoin** [comment]
I dislike the trick you did in start.sh for multiple versions of rebar, because the user might have a different version of rebar installed to their system than we want to use.
I would rather do something like I did in install.sh

**Comment by stefek99** [comment]
> You did

Asked question on StackOverflow.

The intention was to have same script on Ubuntu and Mac.

**Comment by zack-bitcoin** [comment]
ok, I updated the code. hopefully it can run on a mac now.

**Comment by GroundedSage** [comment]
Was legit just querying about this in gitter like yesterday. Thanks for doing docs for mac. Will test it out.

**Comment by GroundedSage** [comment]
I hit an error here. 
`Wades-iMac:testnet Wade$ rebar compile
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
src/consensus/tree/block.erl:2: function guess_number_of_cpu_cores/1 undefined
Compiling src/consensus/tree/block.erl failed:
ERROR: compile failed while processing /Users/wade/testnet: rebar_abort`

**Comment by zack-bitcoin** [comment]
Yes the code was temporarily broken because I removed ./rebar compile from the startup script so the compiler didn't run and I thought it was error free.
If you try running it now, it should download the fresh version of the code and work properly.

**Comment by GroundedSage** [comment]
Hmm. I keep getting this. It seemed to still be working earlier with a lot of forms at the website. Now it seems to just stop me where it asks for a password.

```
=ERROR REPORT==== 13-Apr-2017::02:32:36 ===
Error in process <0.341.0> with exit value:
{[{reason,{badmatch,{error,enoent}}},
  {mfa,{main_handler,handle,2}},
  {stacktrace,[{main_handler,read_file,1,
                             [{file,"src/networking/main_handler.erl"},
                              {line,17}]},
               {main_handler,handle,2,
                             [{file,"src/networking/main_handler.erl"},
                              {line,13}]},
               {cowboy_handler,handler_handle,4,
                               [{file,"src/cowboy_handler.erl"},{line,111}]},
               {cowboy_protocol,execute,4,
                                [{file,"src/cowboy_protocol.erl"},
                                 {line,442}]}]},
  {req,[{socket,#Port<0.2291>},
        {transport,ranch_tcp},
        {connection,keepalive},
        {pid,<0.341.0>},
        {method,<<"GET">>},
        {version,'HTTP/1.1'},
        {peer,{{127,0,0,1},64222}},
        {host,<<"localhost">>},
        {host_info,undefined},
        {port,8041},
        {path,<<"/favicon.ico">>},
        {path_info,undefined},
        {qs,<<>>},
        {qs_vals,undefined},
        {bindings,[{file,<<"favicon.ico">>}]},
        {headers,[{<<"host">>,<<"localhost:8041">>},
                  {<<"connection">>,<<"keep-alive">>},
                  {<<"pragma">>,<<"no-cache">>},
                  {<<"cache-control">>,<<"no-cache">>},
                  {<<"user-agent">>,
                   <<"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36">>},
                  {<<"accept">>,<<"image/webp,image/*,*/*;q=0.8">>},
                  {<<"referer">>,<<"http://localhost:8041/login.html">>},
                  {<<"accept-encoding">>,<<"gzip, deflate, sdch, br">>},
                  {<<"accept-language">>,<<"en-US,en;q=0.8">>}]},
        {p_headers,[{<<"connection">>,[<<"keep-alive">>]}]},
        {cookies,undefined},
        {meta,[]},
        {body_state,waiting},
        {buffer,<<>>},
        {multipart,undefined},
        {resp_compress,false},
        {resp_state,waiting},
        {resp_headers,[]},
        {resp_body,<<>>},
        {onresponse,undefined}]},
  {state,[]}],
 [{cowboy_handler,handler_handle,4,
                  [{file,"src/cowboy_handler.erl"},{line,119}]},
  {cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]}
```
