### ISSUE TITLE
Aportación

### ISSUE THREAD

**Issue by Leonyxtested** [aeternity/testnet#20]
No se donde poner mi siguiente aportacion,seguramente en el fork que tengo de esto pero te lo dejo aqui para que lo mires. Se trata de darle al momento de encontrar un bloque una fecha mas facil de reconocer,el dia y la hora,es un poco bruto y no se si he fastidiado algo que no sepa pero te lo doy:

FOUND A BLOCK !
absorb block ["pow",["block",2210,"SS5ERvb+sd55M6Cp",[-6],"Ad8CUd/PDJ7vBdv9","zZR5o32ZUiySIV0d",[13,"SExteUZIcVViSmM5N0N0TkhQ"],**[[2017,4,8],[18,39,26]]**,6452,"",1],6452,726859429336903248237612]
6> keys:address().
<<"HLmyFHqUbJc97CtNHP">>
7> easy:balance().
["5.36870911"]
8> FOUND A BLOCK !
absorb block ["pow",["block",2211,"b44WlpZUO7SdYLl2",[-6],"Ad8CUd/PDJ7vBdv9","xRCw5SYycAARkGeb",13,**[[2017,4,8],[19,2,24]]**,6452,"",1],6452,600225045680992712400338]
FOUND A BLOCK !
absorb block ["pow",["block",2212,"6RWTmfngMzKBtSBZ",[-6],"Ad8CUd/PDJ7vBdv9","myRsctthN/vtYanN",13,**[[2017,4,8],[19,3,50]]**,6452,"",1],6452,389215466812210250873958]

**Comment by Leonyxtested** [comment]
Perdon,me he equivocado al ponerlo en mi fork,espero no estropearlo mucho.

**Comment by zack-bitcoin** [comment]
padre.
gracias para experimentar.
tienes idea buen, pero pienso nesisitamo hacer un poco diferente.
Quiero tener bloques piquenas. Que haces es mas grande.
Necisitamos software para leer las bloques mas facil. 
Un explorador de bloques.

Cool. Thanks for experimenting.
You have a good idea, but we need to do it a little differently.
We want the blocks to be small, and this edit would make the blocks bigger.
Instead we should make software for reading the blocks in a pretty format.
We need a block explorer.

**Comment by Leonyxtested** [comment]
OK,hacer un explorador de bloques,un blockchain,no?
Si,los bloques son significativamente mas grandes,vere que puedo hacer.

**Comment by zack-bitcoin** [comment]
por ejemplo, este es un explorador de bloques para bitcoin: https://blockchain.info/
El explorador no necisite ser en Erlang. Posibelmente javascript es mejor.

**Comment by Leonyxtested** [comment]
Siento no poder ayudar con javascript,intentare hacer lo que pueda en algun otro aspecto.

**Comment by zack-bitcoin** [comment]
traducir a espanol es bueno. 
Creas un carpeta como "/docs_espanoles"
y me voy a incluir in el proyecto.

Translating to spanish is good.
Make a file like "/spanish_docs" to put all the spanish in.
Then you can do a push request and I will include your writing into the project.

**Comment by Leonyxtested** [comment]
Perfecto,eso me da algo que hacer y que aportar. Por cierto,no hace falta que traduzcas lo que pones,ya lo hago yo ;)

**Comment by Leonyxtested** [comment]
En el documento oracle_off_chain.md he encontrado una ambiguedad que no se que significa.

> If too many of the miner's bets are censored (> ~95%), then the miners censor the oracle from publishing the result.

Esto tiene que ver cuando se invalidan los shares de un minero? si es asi,un minero defectuoso puede censurar oraculos sin saberlo.

**Comment by zack-bitcoin** [comment]
donde leas este? 
pienso este documento es antiguo. 
necisito arreglarlo. 

Busco con grep, y no puedo encontrarlo.

**Comment by Leonyxtested** [comment]
Si,es un documento antiguo,el brand que tengo puesto se ha quedado antiguo,voy a cambiarlo todo al maestro de mi fork que veo que se actualiza
