### ISSUE TITLE
Web interface should run on standard port (80, 443) so that it is open by default on VPS hosting services?

### ISSUE THREAD

**Issue by stefek99** [aeternity/testnet#21]
Currently it's some random port.

What's the reason?

If I want to run the node on some server, I would like to access web interface without messing with the firewall.

Standard ports such as 80 or 443 are open by default.

**Comment by Leonyxtested** [comment]
Lo logico sera usar los puertos estandar,para eso se hicieron.

**Comment by zack-bitcoin** [comment]
On the servers I have used they always leave open the low 8000s.
We don't recommend running the node as root. Ports 80 and 443 usually require root.

My experience is in development, not operations. So could be making the wrong choice here, maybe we should be running as root.

**Comment by Leonyxtested** [comment]
Depende del servidor,si pertenece al equipo puede pasar por el puerto 80 y 443 configurando el firewall y haciendo usuarios a los cuales se les limita el movimiento dentro del servidor.
Si es de un tercero lo mejor sera adaptarse a sus condiciones y usar puertos libres por encima del 8000.

**Comment by zack-bitcoin** [comment]
You can choose the port when you start the node
Here is how to use 80

sh start.sh 80

puedes escoger el puerto cuando comienzo el nodo.

**Comment by Leonyxtested** [comment]
Esto me ha pasado cuando he probado:

ubuntu@Desktop:~/testnet$ sh start.sh 80
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
GO TO THIS WEBSITE -------> http://localhost:8041/login.html
Erlang/OTP 18 [erts-7.3.1.2] [source] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3.1.2  (abort with ^G)
1> start keys
start toptx pool started
changing port!!!
changing port!!!
start server
{"init terminating in do_boot",{{badmatch,{error,{{shutdown,{failed_to_start_child,ranch_acceptors_sup,{{badmatch,{error,eacces}},[{ranch_acceptors_sup,init,1,[{file,"src/ranch_acceptors_sup.erl"},{line,30}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,287}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}},{child,undefined,{ranch_listener_sup,http_internal},{ranch_listener_sup,start_link,[http_internal,100,ranch_tcp,[{ip,{0,0,0,0}},{port,81}],cowboy_protocol,[{env,[{dispatch,[{'_',[],[{[file],[],main_handler,[]},{[],[],internal_handler,[]}]}]}]}]]},permanent,infinity,supervisor,[ranch_listener_sup]}}}},[{serve,start,1,[{file,"src/networking/serve.erl"},{line,28}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,122}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done

**Comment by zack-bitcoin** [comment]
The node uses 2 port numbers. One for communication on the same node, and one for letting the outside world contact you.
It looks like your computer blocks access to port 81.

Pienso no puedes usar puerto 81 con este computadora.
Aeternity nesesita dos puertos.

**Comment by stefek99** [comment]
> Ports 80 and 443 usually require root.

We don't need to worry about it right now.

Also related to #23 and #10

**Comment by zack-bitcoin** [comment]
It is easy to use whatever 2 adjacent ports you want. For example, if you want 4444 and 4445:
sh start.sh 4444

**Comment by stefek99** [comment]
This isssue was about default VPS configuration.
