### ISSUE TITLE
README.md link to aeternity.com broken

### ISSUE THREAD

**Issue by adrelanos** [aeternity/testnet#22]
https://github.com/aeternity/testnet/blob/master/README.md

> This is the code used for the testnet for the [æternity](www.aeternity.com) project.

For some unknown reason this links to https://github.com/aeternity/testnet/blob/master/www.aeternity.com.

**Comment by Leonyxtested** [comment]
Es cierto

**Comment by zack-bitcoin** [comment]
Great, thanks. I fixed it.
