### ISSUE TITLE
Automatizar autoarranque?

### ISSUE THREAD

**Issue by Leonyxtested** [aeternity/testnet#24]
Como muchas veces se ejecutan los mismo comandos,personalmente me gustaria añadir un lanzador y un script que realice esto. El lanzador ya lo tengo,en un click se arranca el nodo.

Seria bueno automatizar los comandos easy:sync(). mine:start(). y easy:balance(). ?

**Comment by zack-bitcoin** [comment]
If you think different syntax would be better, please suggest it.
What would be easier than typing `mine:start()` to start the miner?
How would you like to look up you balance?

que quieres? no se que formato es mejor.

**Comment by Leonyxtested** [comment]
Los comandos estan bien desde mi punto de vista.

Pienso,y espero hacerlo para probarlo,que se podria hacer un script que al usar `start.sh` al terminar de arrancar el nodo tambien se sincronizara, arrancara el minero y pusiera el comando `easy:account()`.
O que en el archivo `start.sh` ya viniera incluido que hiciera esto,no se,yo lo que he leido es que se usa un scrypt.

Algo como esto: 
#!/usr/bin/env escript
main([]) ->
io:format("Usage: fact <number>~n~n"),
1;
main([NumberTxt]) ->
try
Number = list_to_integer(NumberTxt),
io:format("~p! = ~p~n", [Number, fact(Number)]),
0
catch
error:badarg -> main([])
end.
fact(1) -> 1;
fact(N) -> N * fact(N-1).

**Comment by zack-bitcoin** [comment]
muchos personas no quieren minerar.
Most people don't want to mine, so I don't want the miner to turn on by default.
It makes my computer too hot. The heat wears out my battery.

I don't know why you wrote code for printing out the factorial of a big number.
No se porque escribes esto scrypt.

**Comment by Leonyxtested** [comment]
Es un ejemplo sacado de un manual,nada que ver con esto.
Entiendo,nada de mineria,sincronizar y revisar la cuenta? Es una sugerencia
