### ISSUE TITLE
Add makefile target for unit tests

### ISSUE THREAD

**Issue by sennui** [aeternity/testnet#242]
Run it in TravisCi

**Comment by cytadela8** [comment]
What do you mean? In TravisCi we run 'make tests'

**Comment by sennui** [comment]
right, these are the integration test in /tests

We want to run our equivalent of unit tests.
By hand you can do it by attaching to one node (after its started fresh and clean) and run tester:test()

We should migrate tester to regular eunit tests (or common tests), but thats not the scope of this ticket

**Comment by cytadela8** [comment]
We should then maybe add some new command to Makefile to do that? (if that's possible)

**Comment by lucafavatella** [comment]
In https://github.com/aeternity/testnet/pull/253/files#diff-354f30a63fb0907d4ad57269548329e3R14 - already merged - I hooked running Makefile target `unit-tests` in CI, allowing its failure. That target attempts to run both eunit and ct. Eunit finds no tests and passes. Ct finds no tests and fails.

I understand no decision has been taken yet on whether to prefer eunit or ct.

**Comment by lucafavatella** [comment]
See also #238

**Comment by cytadela8** [comment]
@lucafavatella. So #253 should have closed this? = We should close this as it's finished

**Comment by lucafavatella** [comment]
> @lucafavatella. So #253 should have closed this? = We should close this as it's finished?

@cytadela8 Yes in my opinion (I had not seen this ticket when opening the PR).

**Comment by cytadela8** [comment]
Then I'm closing it.

**Comment by cytadela8** [comment]
@sennui Please check if that's indeed closed.
