### ISSUE TITLE
Error in process ___ with exit value ••• {{badmatch,{error,failed_connect}} ••• {badarg,[{erlang,'++',

### ISSUE THREAD

**Issue by stefek99** [aeternity/testnet#26]
```
=ERROR REPORT==== 8-Apr-2017::11:59:49 ===
Error in process <0.11710.0> with exit value:
{{badmatch,{error,failed_connect}},
 [{download_blocks,trade_blocks,4,
                   [{file,"src/consensus/download_blocks.erl"},{line,68}]},
  {download_blocks,sync,3,
                   [{file,"src/consensus/download_blocks.erl"},{line,38}]}]}
 
=ERROR REPORT==== 8-Apr-2017::11:59:49 ===
Error in process <0.9625.0> with exit value:
{{badmatch,{error,failed_connect}},
 [{download_blocks,trade_blocks,4,
                   [{file,"src/consensus/download_blocks.erl"},{line,68}]},
  {download_blocks,sync,3,
                   [{file,"src/consensus/download_blocks.erl"},{line,38}]}]}
 
=ERROR REPORT==== 8-Apr-2017::11:59:49 ===
Error in process <0.3209.0> with exit value:
{badarg,[{erlang,'++',
                 [ok,
                  [{pow,{block,612,
                               <<201,195,159,44,141,150,112,16,37,47,136,52>>,
                               [],
                               <<1,223,2,81,223,207,12,158,239,5,219,253>>,
                               <<41,36,171,67,12,7,80,70,134,197,176,94>>,
                               7,10779243,6452,<<>>,1},
                        6452,603963384520894636866814},
```

Full log: https://pastebin.com/ZGgbKH1t

I was on the train while running it so maybe some connectivity issues.

**Comment by Leonyxtested** [comment]
Me esta pasando lo mismo,pero aun asi sigue encontrando bloques,pienso que es un fallo que hay por no conectarese a ningun servidor donde descargar todos los bloques cuando sincroniza. Erlang es capaz de seguir a delante incluso con ese error. Puedes encontrar bloques?

**Comment by zack-bitcoin** [comment]
Leonyxtested is right. This error is not stopping your node from running properly.
Erlang uses fail-fast strategy. If something goes wrong, we don't want to waste time on it.
We fail fast and get ready to handle the next command.

I updated the experimental branch so that this error wont occur any more, which should increase download speeds for poorly connected nodes.
After the next hard fork this will be fixed on the testnet too.

**Comment by zack-bitcoin** [comment]
It looks like there are so many people on the testnet that it is slowing down.
