### ISSUE TITLE
GET http://localhost:8041/favicon.ico 500 (Internal Server Error)

### ISSUE THREAD

**Issue by stefek99** [aeternity/testnet#30]
Cosmetic...

**Comment by zack-bitcoin** [comment]
Please stop spamming the issues.

**Comment by stefek99** [comment]
Easier done than said.

It could be a red herring - some unrelated error exposing some misconfiguration.

From experience I know that users tend to report any errors they encounter.

**Comment by zack-bitcoin** [comment]
The html is not used.
It is a simple example to help the javascript light wallet designers know how the pieces fit together.
