### ISSUE TITLE
POST http://localhost:8041/ 500 (Internal Server Error) - Ranch listener http_internal had connection process started with cowboy_protocol

### ISSUE THREAD

**Issue by stefek99** [aeternity/testnet#31]
Related to #10 

Wanted to see what API methods are available.

It seems like I cannot start the thing.

![image](https://cloud.githubusercontent.com/assets/249703/24894537/f02461a0-1e82-11e7-8f02-55ac550977a2.png)

Here is the error log: https://gist.github.com/stefek99/2b009e64a45d7d6d8bb7ad4af932b759

**Comment by zack-bitcoin** [comment]
looks like you are using the wrong password.
Do you even make a password yet?

The html stuff is very unfinished, and it will be completely remade as a javascript light wallet that doesn't depend on a local node.

If you want to see what API commands are available, then look at these files:
https://github.com/aeternity/testnet/blob/master/src/networking/handler.erl
https://github.com/aeternity/testnet/blob/master/src/networking/internal_handler.erl

**Comment by zack-bitcoin** [comment]
Please, only use this issues for things to help new programmers know how to get started.
If you have specific questions or comments, feel free to email me instead.

**Comment by stefek99** [comment]
These are all usability blunders!

If the password is wrong - say `wrong password` instead, do not throw 500 `internal server error`

**Comment by zack-bitcoin** [comment]
Shall I delete all these examples because they arent usable enough?
I thought that the javascript wallet designer would appreciate all the example code I made, but if it is too distracting I can let the wallet designer start from scratch.

**Comment by stefek99** [comment]
I'm sorry.

In my personal communication policy - I do not allow irony, sarcasm and rhetorical questions.

> Shall I delete all these examples because they arent usable enough?

_(sounds like rhetorical question)_

Even the Javascript wallet designers #10 may use a wrong password... And then the server side will return `500` as well.

---

We spend collectively at least 10 hours commenting on various issues, yesterday I had some time at 19:06, Today busy, tomorrow evenining - possible. 

I'm not sitting in your head.
