### ISSUE TITLE
keys:unlock error 

### ISSUE THREAD

**Issue by tclauss** [aeternity/testnet#45]
Hi @zack-bitcoin,

When i try to unlock with a wrong pwd I get the next error instead a more friendly message. Is that the normal flow ?

`9> keys:unlock("wrong_pwd").     
keys diedok

=ERROR REPORT==== 18-Apr-2017::11:08:26 ===
** Generic server keys terminating 
** Last message in was {'$gen_cast',{unlock,"wrong_pwd"}}
** When Server state == [{[],[{"State",[]}]}]
** Reason for termination == 
** {badarg,[{erlang,binary_to_term,
                    [<<178,98,111,103,252,104,187,97,0,156,155,38,214,182,168,
                       156,169,64,197,207,234,7,242,128,9,115,227,7,79,85,190,
                       253,171,209,23,210,220,25,88,148,120,154,228,199,26,60,
                       165,222,45,209,4,244,209,218,36,50,138,172,238,240,78,
                       90,228,62,141,213,244,77,77,79,213,104,227,148,17,74,
                       248,103,190,95,134,155,36,49,56,96,148,230,160,221,252,
                       28,71,209,187,115,54,254,166,19,209,241,246,62,248,173,
                       208,249,98,58,137,82,171,212,196,194,9,138,161,58,108,
                       244,5,153,79,170,185,221,242,137,190,211,178,221,210,
                       68,70,49,95,200,25,200,54,112,199,172,222,210,42,3,91,
                       47,54,151,201,23,236,31,250,3,148,242,229,174,92,253,
                       79,214,75,189,135,22,29,129,4,89,148,17,62,86,202,46,
                       146,15,57,45,160,172,240,113,87,226,19,174,139,110,132,
                       16,226,64,87,102,240,192,68,49,209,1,71,117,210,249,19,
                       204>>],
                    []},
            {encryption,sym_dec,2,[{file,"src/encryption.erl"},{line,19}]},
            {encryption,get_msg,2,[{file,"src/encryption.erl"},{line,28}]},
            {encryption,decrypt,2,[{file,"src/encryption.erl"},{line,43}]},
            {keys,handle_cast,2,[{file,"src/consensus/keys.erl"},{line,74}]},
            {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
            {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
start keys
10> 
`

**Comment by zack-bitcoin** [comment]
The normal flow is to use the api to communicate with the node.
The code is written in erlang, which uses the fail fast philosophy.
So it is supposed to have errors messages like this.
