### ISSUE TITLE
api should be encrypted

### ISSUE THREAD

**Issue by zack-bitcoin** [aeternity/testnet#46]
To protect the sensitive channel data from being released, we should make the entire api encrypted.
There is already an encryption library being used for keys.erl, we can use it for this too.

**Comment by Leonyxtested** [comment]
Si lo que he leido bien en keys.erl, el uso de una clave publica y privada es lo mas seguro, y ya ciframos nuestras cuentas con una clave para generar las claves publicas y privadas.

**Comment by sennui** [comment]
ssl
