### ISSUE TITLE
unresolved functions

### ISSUE THREAD

**Issue by Zwilla** [aeternity/testnet#47]
Hi Zack,

I found this unresolved functions, is it normal or do I have to setup my IDE better?
Which IDE do you use?

accounts:balance
accounts:nonce
accounts:update
accounts:addr

block_tree:account
block_tree:channel
block_tree:height
block_tree:read_int
block_tree:txs
block_tree:buy_block

channel_feeder:simplify

channels:acc1
channels:acc2
channels:bal1
channels:bal2
channels:empty
channels:read_channel

channel_manager:id
channel_manager:read_channel

channel_manager_feeder:recieve
channel_manager_feeder:spend_account

channel_slash_tx:channel_block

channel_solo_close:make

channel_slash_tx:make

channel_timeout:make

channel_timeout_tx:channel_block

compiler:compile

constants:blocks
constants:block_pointers
constants:accounts
constants:all_secrets
constants:d_accounts
constants:channels
constants:d_channels
constants:entropy

create_account_tx:create_account

dict:delete
dict:remove

encryption:get_msg

free_variables:bets

hash:doit
hash:file
hash:hash_depth

keys:sign

language:assemble
language:run_script

new_channel_tx:make

spend_tx:spend

sign_tx:sign

tx_pool:accounts

**Comment by zack-bitcoin** [comment]
I use emacs.
There is some old code that is currently unused, like mail.erl
It calls old commands that no longer exist.
