### ISSUE TITLE
keys:id(). returns -1 after the fresh start ••• keys:pubkey(). and keys:address(). are fine

### ISSUE THREAD

**Issue by stefek99** [aeternity/testnet#50]
Here is the problematic line:

```
keys:id().
-1
```

Full call stack:

```
Michals-MacBook-Pro:testnet zen$ sh clean.sh
Michals-MacBook-Pro:testnet zen$ sh start.sh
From https://github.com/aeternity/testnet
 * branch            master     -> FETCH_HEAD
Already up-to-date.
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V8.3  (abort with ^G)
1> start keys
start toptx pool started
start server
keys:status().
locked
2> keys:id().
-1
3> keys:pubkey().
<<"BNrbq/0lx52Wg1CAy3tGSTrrrWSw7fiMenhfSvM3dguyoSo/039h4gugjMPHti4QX93CS37CwUiNyTxF9efWUt0=">>
4> keys:address().
<<"KCBUrpiRjSAuHJG1sL">>
```

Maybe I need to clean deeper?

I'm actually that I have something after restart, previously I thought it is removed.

**Comment by Zwilla** [comment]
load(Pub, Priv, Brainwallet) -> gen_server:cast(?MODULE, {load, Pub, Priv, Brainwallet}).
There is no ID
For this use:
keys:load(<<„BOvirXmgmU1pCZlBFB+oSws/g4S8UTtJj9zPCUsn46tE7tACkXK0xf0HmFPuh67icS2oplsWAoOTzYyPsdYWhk0=">>, <<"unnAC3L4mSKqZXj6+XIy0XENQTkacv3R1kn+9U7OKQw=">>, "abc").

Point one: we need to change the keys:load instructions on keys.md or add here the ID

**Comment by Zwilla** [comment]
take a look to my sh scripts. Updated right now!
[https://github.com/Zwilla/aeternity-testnet](url)

**Comment by Zwilla** [comment]
do this:
`keys:pubkey().`
you get something like this:
`<<„BOvirXmgmU1pCZlBFB+oSws/g4S8UTtJj9zPCUsn46tE7tACkXK0xf0HmFPuh67icS2oplsWAoOTzYyPsdYWhk0=„>>`
now do this:
`keys:shared_secret(<<„BOvirXmgmU1pCZlBFB+oSws/g4S8UTtJj9zPCUsn46tE7tACkXK0xf0HmFPuh67icS2oplsWAoOTzYyPsdYWhk0=„>>).`

The result is your privat key like this:
`<<„unnAC3L4mSKqZXj6+XIy0XENQTkacv3R1kn+9U7OKQw=">>`

Remember the default password (var Brainwallet) is „abc“.

Now you have all to load a wallet like this:
`keys:load(<<"BOvirXmgmU1pCZlBFB+oSws/g4S8UTtJj9zPCUsn46tE7tACkXK0xf0HmFPuh67icS2oplsWAoOTzYyPsdYWhk0=">>, <<"unnAC3L4mSKqZXj6+XIy0XENQTkacv3R1kn+9U7OKQw=">>, "abc").`

**Comment by zack-bitcoin** [comment]
@Zwilla 
`keys:shared_secret()` is an internal function. you are not supposed to use it. It is for doing secure encryption.
It does not create your private key.

The default password is "" the empty list, not "abc".

**Comment by zack-bitcoin** [comment]
@stefek99 yes, you don't have money. you haven't mined blocks. you don't have an account. so it is supposed to say -1.

**Comment by stefek99** [comment]
Just imagine my experience...

![image](https://cloud.githubusercontent.com/assets/249703/25280184/f438e3ee-26a0-11e7-9c23-6f53ef4a3a78.png)

I think we need more user-friendly messages...

And maybe some crash reporting...

User-friendly message to the user, crash log for developers.
