### ISSUE TITLE
Fix /docs/keys.md or fix keys:load function, please.

### ISSUE THREAD

**Issue by Zwilla** [aeternity/testnet#51]
To load a private key into an existing node:

this does not work atm:
`keys:load(Pubkey, Privkey, „password“, ID).`
Result: undefined function keys:load/4

this works:
`keys:load(Pubkey, Privkey, „password“).`
Result: function keys:load/3 exists.

**Comment by zack-bitcoin** [comment]
Great! Thank you Zwilla
