### ISSUE TITLE
type system

### ISSUE THREAD

**Issue by zack-bitcoin** [aeternity/testnet#52]
By adding types to all the function inputs and outputs we can fix a lot of bugs in the code.
I think this is the tool we want to use for this http://erlang.org/doc/man/dialyzer.html

**Comment by sjamayee** [comment]
Is this as simple as:
1. Run typer on every file
2. Paste the function spec for every function/file
3. Eventually adjust/narrow manually (if in/outs are clear and well understood!)
If this is of any help, I could do it.

**Comment by zack-bitcoin** [comment]
Those could be the steps, I am not sure. I don't know what "typer" is.
I haven't programmed in strongly typed languages much before.

If you could use dialyzer on even just 1 file, then I will understand what is going on and can do it to the rest.

**Comment by sjamayee** [comment]
Typer is just another erlang tool, which generates the type/spec for a module.

iMac:src jac$ typer dice.erl
...
%% File: "dice.erl"
%% ----------------
-spec make_ss(_,binary()) -> any().
-spec resolve_ss(_,_,_) -> any().

Just pasting all specs on top, would be good to start with...

**Comment by lucafavatella** [comment]
This is where the type and function specifications are documented http://erlang.org/doc/reference_manual/typespec.html

**Comment by sennui** [comment]
too general issue.
