### ISSUE TITLE
easy:sync(). crash

### ISSUE THREAD

**Issue by tclauss** [aeternity/testnet#54]
Eshell V8.2.1  (abort with ^G)
1> start keys
start toptx pool started
start server
easy:balance().
["2442.70022201"]
2> keys:address().
<<"Hw1EqCV9BsQEp1rCjP">>
3> keys:unlock("******").
ok
4> easy:sync().
<0.342.0>
syncing with peercheck top5> absorb block ["pow",["block",1093,"5joa2HC7kiLbwa29",[-6],"XYnwVoZQUry4nJEN","tSBY6mJiDzodgXLE",8,103800941,6452,"",1],6452,72620055846470876531070]
died!
=ERROR REPORT==== 24-Apr-2017::12:19:14 ===
** Generic server block_absorber terminating 
** Last message in was {'$gen_cast',
                           {doit,
                               {pow,
                                   {block,1093,
                                       <<230,58,26,216,112,187,146,34,219,193,
                                         173,189>>,
                                       [],
                                       <<93,137,240,86,134,80,82,188,184,156,
                                         145,13>>,
                                       <<181,32,88,234,98,98,15,58,29,129,114,
                                         196>>,
                                       8,103800941,6452,<<>>,1},
                                   6452,72620055846470876531070}}}
** When Server state == []
** Reason for termination == 
** {{badmatch,false},
    [{block,check2,1,[{file,"src/consensus/tree/block.erl"},{line,221}]},
     {block_absorber,absorb,1,
                     [{file,"src/consensus/tree/block_absorber.erl"},
                      {line,31}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/tree/block_absorber.erl"},
                      {line,14}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

**Comment by zack-bitcoin** [comment]
It looks like you are using an old version of the code.
Completely reinstall from github.

**Comment by tclauss** [comment]
yep. work now.

**Comment by tclauss** [comment]
@zack-bitcoin the problem was in my side :-) For testing I use a VM, and when stop the VM to  restart later, next time when start again the VM, the ubuntu start with time/date of the last time (the OS time is not up to date) ... so in this case sync crash because the block_time > actual_time(os_time is not up to date) .... true ?

**Comment by zack-bitcoin** [comment]
It is cool that you were able to diagnosis that.
