### ISSUE TITLE
mine:start(). error

### ISSUE THREAD

**Issue by tclauss** [aeternity/testnet#59]
Hi @zack-bitcoin 

After reinstalling the new testnet I get the following error when I try to start the mining process (before was executed easy:sync()):

testnet@aeternity:~/testnet$ sh start.sh 
From https://github.com/aeternity/testnet
 * branch            master     -> FETCH_HEAD
Already up-to-date.
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:3:3] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.2.1  (abort with ^G)
1> start keys
start toptx pool started
start server
2> keys:unlock("*****").
ok
3> mine:start().
start mining with 3 cores.
ok
4> 
=ERROR REPORT==== 28-Apr-2017::12:39:16 ===
Error in process <0.419.0> with exit value:
{{badmatch,{{trees,1,0,0,0,0,38},4,[]}},
 [{block,new_id,1,[{file,"src/consensus/chain/block.erl"},{line,376}]},
  {block,mine_blocks,2,[{file,"src/consensus/chain/block.erl"},{line,403}]},
  {mine,'-handle_cast/2-fun-0-',0,
        [{file,"src/consensus/mine.erl"},{line,13}]}]}
top of sync
top of sync
got topblock

**Comment by zack-bitcoin** [comment]
I made a mistake with the hard fork, so the testnet was unusable for a couple of hours. It should work fine now. You need to completely reinstall from github.

**Comment by tclauss** [comment]
@zack-bitcoin , reinstalled but nort work :-( same error ...

testnet@aeternity:~/testnet$ sh start.sh 
From https://github.com/aeternity/testnet
 * branch            master     -> FETCH_HEAD
Already up-to-date.
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:3:3] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.2.1  (abort with ^G)
1> start keys
start toptx pool started
start server
keys:new("****").
ok
start keys
3> keys:unlock("*****").
ok
4> easy:sync().
<0.420.0>
top of sync
top of sync
got topblock
5> absorb block ["block_plus",["block",1,"Piyq3Xqa0iSBREj8",[-6],"Vh+Pjkkcy9DjdBma",1,107970479,6452,"",1],["pow","Piyq3Xqa0iSBREj8AAAAAQAAAAAAAAAAAAAAAQZvf68AGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,27756214415815050790505],["trees",1,0,0,0,0,38],40370176,["prev_hashes","Piyq3Xqa0iSBREj8"]]
absorb block ["block_plus",["block",2,"AGiEA++lNJhXHnnY",[-6],"Vh+Pjkkcy9DjdBma",1,107979978,6452,"",1],["pow","AGiEA++lNJhXHnnYAAAAAgAAAAAAAAAAAAAAAQZvpMoAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,627868530292918450614450],["trees",1,0,0,0,0,38],80740352,["prev_hashes","AGiEA++lNJhXHnnY"]]
absorb block ["block_plus",["block",3,"/5h44wWzMgvAhIaV",[-6],"Vh+Pjkkcy9DjdBma",1,107980504,6452,"",1],["pow","/5h44wWzMgvAhIaVAAAAAwAAAAAAAAAAAAAAAQZvptgAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,981719795042820681791473],["trees",1,0,0,0,0,38],121110528,["prev_hashes","/5h44wWzMgvAhIaV"]]
absorb block ["block_plus",["block",4,"I7Xk0nyZlJdxX++1",[-6],"Vh+Pjkkcy9DjdBma",1,107982828,6452,"",1],["pow","I7Xk0nyZlJdxX++1AAAABAAAAAAAAAAAAAAAAQZvr+wAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,826879760670190574984334],["trees",1,0,0,0,0,38],161480704,["prev_hashes","I7Xk0nyZlJdxX++1","AGiEA++lNJhXHnnY"]]
top of sync
top of sync
got topblock
5> mine:start().
start mining with 3 cores.
ok
6> 
=ERROR REPORT==== 28-Apr-2017::13:27:17 ===
Error in process <0.481.0> with exit value:
{{badmatch,{{trees,1,0,0,0,0,38},4,[]}},
 [{block,new_id,1,[{file,"src/consensus/chain/block.erl"},{line,376}]},
  {block,mine_blocks,2,[{file,"src/consensus/chain/block.erl"},{line,403}]},
  {mine,'-handle_cast/2-fun-0-',0,
        [{file,"src/consensus/mine.erl"},{line,13}]}]}
top of sync
top of sync
got topblock

**Comment by zack-bitcoin** [comment]
Yes, you are correct.
This bug didn't happen to me because I was using account 1, which already exists.
It is a bug that only happened when you try making a new account.
Thank you for the help.

**Comment by zack-bitcoin** [comment]
If you restart your node now, it should work properly.

**Comment by tclauss** [comment]
@zack-bitcoin  reinstalled, but crash again .... another error.

testnet@aeternity:~/testnet$ sh start.sh 
From https://github.com/aeternity/testnet
 * branch            master     -> FETCH_HEAD
Already up-to-date.
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:3:3] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.2.1  (abort with ^G)
1> start keys
start toptx pool started
start server
keys:new("aeternity_key").
ok
2> keys:unlock("aeternity_key").
ok
3> easy:sync().
<0.418.0>
top of sync
got topblock
4> absorb block ["block_plus",["block",1,"Piyq3Xqa0iSBREj8",[-6],"Vh+Pjkkcy9DjdBma",1,107970479,6452,"",1],["pow","Piyq3Xqa0iSBREj8AAAAAQAAAAAAAAAAAAAAAQZvf68AGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,27756214415815050790505],["trees",1,0,0,0,0,38],40370176,["prev_hashes","Piyq3Xqa0iSBREj8"]]
absorb block ["block_plus",["block",2,"AGiEA++lNJhXHnnY",[-6],"Vh+Pjkkcy9DjdBma",1,107979978,6452,"",1],["pow","AGiEA++lNJhXHnnYAAAAAgAAAAAAAAAAAAAAAQZvpMoAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,627868530292918450614450],["trees",1,0,0,0,0,38],80740352,["prev_hashes","AGiEA++lNJhXHnnY"]]
absorb block ["block_plus",["block",3,"/5h44wWzMgvAhIaV",[-6],"Vh+Pjkkcy9DjdBma",1,107980504,6452,"",1],["pow","/5h44wWzMgvAhIaVAAAAAwAAAAAAAAAAAAAAAQZvptgAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,981719795042820681791473],["trees",1,0,0,0,0,38],121110528,["prev_hashes","/5h44wWzMgvAhIaV"]]
absorb block ["block_plus",["block",4,"I7Xk0nyZlJdxX++1",[-6],"Vh+Pjkkcy9DjdBma",1,107982828,6452,"",1],["pow","I7Xk0nyZlJdxX++1AAAABAAAAAAAAAAAAAAAAQZvr+wAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,826879760670190574984334],["trees",1,0,0,0,0,38],161480704,["prev_hashes","I7Xk0nyZlJdxX++1","AGiEA++lNJhXHnnY"]]
absorb block ["block_plus",["block",5,"tvvchSn5Pvvz+vOV",[-6],"Vh+Pjkkcy9DjdBma",1,108049638,6452,"",1],["pow","tvvchSn5Pvvz+vOVAAAABQAAAAAAAAAAAAAAAQZwtOYAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,216823205900175559096121],["trees",1,0,0,0,0,38],201850880,["prev_hashes","tvvchSn5Pvvz+vOV","/5h44wWzMgvAhIaV"]]
top of sync
top of sync
got topblock
4> mine:start().
start mining with 3 cores.
top of sync
top of sync
ok
5> 
=ERROR REPORT==== 28-Apr-2017::13:52:27 ===
Error in process <0.453.0> with exit value:
{badarg,[{block,block_to_header,1,
                [{file,"src/consensus/chain/block.erl"},{line,32}]},
         {block,mine2,2,[{file,"src/consensus/chain/block.erl"},{line,166}]},
         {block,mine,2,[{file,"src/consensus/chain/block.erl"},{line,155}]},
         {block,'-mine_blocks/2-fun-0-',2,
                [{file,"src/consensus/chain/block.erl"},{line,425}]},
         {block,mine_blocks,2,
                [{file,"src/consensus/chain/block.erl"},{line,433}]},
         {mine,'-handle_cast/2-fun-0-',0,
               [{file,"src/consensus/mine.erl"},{line,13}]}]}

=ERROR REPORT==== 28-Apr-2017::13:52:27 ===
Error in process <0.465.0> with exit value:
{badarg,[{block,block_to_header,1,
                [{file,"src/consensus/chain/block.erl"},{line,32}]},
         {block,mine2,2,[{file,"src/consensus/chain/block.erl"},{line,166}]},
         {block,mine,2,[{file,"src/consensus/chain/block.erl"},{line,155}]},
         {block,'-mine_blocks/2-fun-0-',2,
                [{file,"src/consensus/chain/block.erl"},{line,425}]}]}

=ERROR REPORT==== 28-Apr-2017::13:52:27 ===
Error in process <0.466.0> with exit value:
{badarg,[{block,block_to_header,1,
                [{file,"src/consensus/chain/block.erl"},{line,32}]},
         {block,mine2,2,[{file,"src/consensus/chain/block.erl"},{line,166}]},
         {block,mine,2,[{file,"src/consensus/chain/block.erl"},{line,155}]},
         {block,'-mine_blocks/2-fun-0-',2,
                [{file,"src/consensus/chain/block.erl"},{line,425}]}]}
got topblock

**Comment by zack-bitcoin** [comment]
Yes, you are right again.
It is because headers have to be computed slightly differently for the blocks where miners don't have accounts yet.
Thank you

**Comment by zack-bitcoin** [comment]
ok, I pushed an update, so it should work for you now.
