### ISSUE TITLE
easy:sync() seems to stop after block 7.

### ISSUE THREAD

**Issue by sjamayee** [aeternity/testnet#60]
After a clean install.
I got this:
3> easy:sync().
<0.424.0>
4> absorb block ["block_plus",["block",1,"Piyq3Xqa0iSBREj8",[-6],"Vh+Pjkkcy9DjdBma",1,107970479,6452,"",1],["pow","Piyq3Xqa0iSBREj8AAAAAQAAAAAAAAAAAAAAAQZvf68AGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,27756214415815050790505],["trees",1,0,0,0,0,38],40370176,["prev_hashes","Piyq3Xqa0iSBREj8"]]
absorb block ["block_plus",["block",2,"AGiEA++lNJhXHnnY",[-6],"Vh+Pjkkcy9DjdBma",1,107979978,6452,"",1],["pow","AGiEA++lNJhXHnnYAAAAAgAAAAAAAAAAAAAAAQZvpMoAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,627868530292918450614450],["trees",1,0,0,0,0,38],80740352,["prev_hashes","AGiEA++lNJhXHnnY"]]
absorb block ["block_plus",["block",3,"/5h44wWzMgvAhIaV",[-6],"Vh+Pjkkcy9DjdBma",1,107980504,6452,"",1],["pow","/5h44wWzMgvAhIaVAAAAAwAAAAAAAAAAAAAAAQZvptgAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,981719795042820681791473],["trees",1,0,0,0,0,38],121110528,["prev_hashes","/5h44wWzMgvAhIaV"]]
absorb block ["block_plus",["block",4,"I7Xk0nyZlJdxX++1",[-6],"Vh+Pjkkcy9DjdBma",1,107982828,6452,"",1],["pow","I7Xk0nyZlJdxX++1AAAABAAAAAAAAAAAAAAAAQZvr+wAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,826879760670190574984334],["trees",1,0,0,0,0,38],161480704,["prev_hashes","I7Xk0nyZlJdxX++1","AGiEA++lNJhXHnnY"]]
absorb block ["block_plus",["block",5,"tvvchSn5Pvvz+vOV",[-6],"Vh+Pjkkcy9DjdBma",1,108049638,6452,"",1],["pow","tvvchSn5Pvvz+vOVAAAABQAAAAAAAAAAAAAAAQZwtOYAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,216823205900175559096121],["trees",1,0,0,0,0,38],201850880,["prev_hashes","tvvchSn5Pvvz+vOV","/5h44wWzMgvAhIaV"]]
absorb block ["block_plus",["block",6,"pbfsoN431FEixuu1",[-6],"Vh+Pjkkcy9DjdBma",1,108079988,6452,"",1],["pow","pbfsoN431FEixuu1AAAABgAAAAAAAAAAAAAAAQZxK3QAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,134449688261327302303673],["trees",1,0,0,0,0,38],242221056,["prev_hashes","pbfsoN431FEixuu1","I7Xk0nyZlJdxX++1"]]
absorb block ["block_plus",["block",7,"zfVXBXgfjCYvFJ22",[-6],"Vh+Pjkkcy9DjdBma",[2,"RnFKaTNacGJmMVRDeThEOXR5"],108081824,6452,"",1],["pow","zfVXBXgfjCYvFJ22AAAABwAAAAAAAAAAAAAAAgZxMqAAGTQAAVYfj45JHMvQ43QZmkMJvLpWbd5HgRxH+g==",6177,110122160369323503204815],["trees",1,0,0,0,0,38],282591232,["prev_hashes","zfVXBXgfjCYvFJ22","tvvchSn5Pvvz+vOV"]]

Is it stopped or do I have to wait?

**Comment by sjamayee** [comment]
Seems to be OK.
I can start mining.

**Comment by zack-bitcoin** [comment]
yes, we changed a bunch of code and restarted at the first block today.
