### ISSUE TITLE
Balance request

### ISSUE THREAD

**Issue by xpunk303** [aeternity/testnet#65]
hi, i'm getting this when i try to request my balance:

17> easy:balance().          
** exception error: no match of right hand side value {{trees,1,0,0,0,0,38},75,[]}
    in function  easy:account/1 (src/easy.erl, line 222)
    in call from easy:integer_balance/0 (src/easy.erl, line 231)
    in call from easy:balance/0 (src/easy.erl, line 233)

Ubuntu 16.04

**Comment by kalleknast** [comment]
I too get that error (on both 16.04 and 16.10) when I call easy:balance(). before starting the miner (i.e. before calling mine:start().). However, if I first start mining and then call easy:balance(). then the error is not thrown.

**Comment by zack-bitcoin** [comment]
ok, I set it up so if you don't have an account yet, it tells you your balance is zero.
