### ISSUE TITLE
mine:start(). issue

### ISSUE THREAD

**Issue by tclauss** [aeternity/testnet#70]
@zack-bitcoin another issue

talk number top of talk helper
5
top of talk helper
top of talk helper

=ERROR REPORT==== 6-May-2017::02:17:11 ===
Error in process <0.1961.0> with exit value:
{{badmatch,{<<136,169,60,186,20,62,209,18,154,79,45,239>>,
            {acc,2878539404,0,110,<<"H4hkyMr7H8kL5LvRN9">>,2,0,0},
            [{<<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<13,125,255,160,72,128,218,205,92,237,249,25>>,
              <<46,17,115,43,234,59,194,48,141,99,238,239>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>,
              <<0,0,0,0,0,0,0,0,0,0,0,0>>}]}},
 [{block,absorb_txs,5,[{file,"src/consensus/chain/block.erl"},{line,123}]},
  {block,make,3,[{file,"src/consensus/chain/block.erl"},{line,153}]},
  {block,mine_blocks,2,[{file,"src/consensus/chain/block.erl"},{line,429}]},
  {mine,'-handle_cast/2-fun-0-',0,
        [{file,"src/consensus/mine.erl"},{line,13}]}]}
talk number 5
top of talk helper
top of talk helper

**Comment by zack-bitcoin** [comment]
Thank you for pointing this out. It should be fixed now. Just restart your node.

**Comment by tclauss** [comment]
@zack-bitcoin , mining crash again :-(

trade blocks 1
top of sync

=ERROR REPORT==== 7-May-2017::03:03:05 ===
Error in process <0.1673.0> with exit value:
{{badrecord,acc},
 [{account,write,2,[{file,"src/consensus/trees/account.erl"},{line,106}]},
  {block,absorb_txs,3,[{file,"src/consensus/chain/block.erl"},{line,143}]},
  {block,make,3,[{file,"src/consensus/chain/block.erl"},{line,173}]},
  {block,mine_blocks,2,[{file,"src/consensus/chain/block.erl"},{line,435}]},
  {mine,'-handle_cast/2-fun-0-',0,
        [{file,"src/consensus/mine.erl"},{line,13}]}]}
top returnedtrade blocks 1
top of sync

**Comment by tclauss** [comment]
@zack-bitcoin , mining crash again :-(

trade blocks 1
top of sync

=ERROR REPORT==== 7-May-2017::03:03:05 ===
Error in process <0.1673.0> with exit value:
{{badrecord,acc},
 [{account,write,2,[{file,"src/consensus/trees/account.erl"},{line,106}]},
  {block,absorb_txs,3,[{file,"src/consensus/chain/block.erl"},{line,143}]},
  {block,make,3,[{file,"src/consensus/chain/block.erl"},{line,173}]},
  {block,mine_blocks,2,[{file,"src/consensus/chain/block.erl"},{line,435}]},
  {mine,'-handle_cast/2-fun-0-',0,
        [{file,"src/consensus/mine.erl"},{line,13}]}]}
top returnedtrade blocks 1
top of sync

**Comment by tclauss** [comment]
@zack-bitcoin, now, after reinstall, the testnet works fine.
