### ISSUE TITLE
Install instructions for Mac are incomplete

### ISSUE THREAD

**Issue by tjayrush** [aeternity/testnet#71]
These instructions: https://github.com/aeternity/testnet/blob/master/docs/compile_mac.md seem to me to be incomplete.

I think it would be as simple as adding an instruction to the begining to do the git clone command that I found on this page: https://github.com/aeternity/testnet/blob/master/docs/compile_ubuntu.md

But maybe not because the install.sh script did not work either. I had to do a symbolic link from /usr/local/bin/rebar to the local folder and then the install.sh script ran okay (there was no 'rebar' in the local folder). I think brew installed rebar in /usr/local/bin

It seems to be working, but the install was bumpy.

**Comment by zack-bitcoin** [comment]
Thank you. I updated it to make mac install easier.
