### ISSUE TITLE
Installing on Mac causes other programs to stop working.

### ISSUE THREAD

**Issue by tjayrush** [aeternity/testnet#72]
I get these errors, now when I run nearly anything (unrelated software) from command line.

    dyld: Symbol not found: __cg_jpeg_resync_to_restart
       Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
      Expected in: /usr/local/lib/libJPEG.dylib
    in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    Abort trap: 6

I traced the problem down to the install of libjpg which required me to `brew uninstall erlang`, which first required me to `brew uninstall rebar`. But first I had to `brew uninstall wxmac` and then I could finally `brew uninstall libjpeg`. And then things started working again. Excruciating. You should  warn people that installing erlang on Mac may cause problems, or remove the instructions for Mac all together until it's better figure out.

**Comment by stefek99** [comment]
I submitted instructions for Mac: https://github.com/aeternity/testnet/pull/29

Then it landed here: https://github.com/aeternity/testnet/blob/master/docs/compile_mac.md

I never liked solving dependencies, build issues, config problems.

How come `libjpeg` is messing up with your existing software?

**Comment by tjayrush** [comment]
I think the problem was the install of `erlang`. When I removed `erlang` the problem went away. I removed stuff with `brew uninstall ...`

**Comment by Zwilla** [comment]
for some reasons I have to use sudo on osx. Try it!

Take a look to my script here: [https://github.com/Zwilla/aeternity-testnet/blob/master/start.sh](url)

**Comment by zack-bitcoin** [comment]
This software is not intended to be run with sudo, that is a security risk.

**Comment by zack-bitcoin** [comment]
I fixed the mac install process so that you no longer use brew. Hopefully it fixed this problem.

**Comment by tjayrush** [comment]
@Zwilla The link above goes to a 404 page not found

**Comment by Zwilla** [comment]
fixed! Thx! 
Please read also this: [Testnet-setup-start-and-use](../../../../aeternity/wiki/wiki/Testnet-setup-start-and-use))
