### ISSUE TITLE
easy:sync(). fetches a few blocks and then stops forever without error message

### ISSUE THREAD

**Issue by adrelanos** [aeternity/testnet#73]
What is the best (latest) aeternity testnet block number?

syncs for me until block 36 (in a Whonix VM) and until block 34 in a Debian stretch VM. Then just stops, doing nothing, no error.

(Cloned a fresh testnet git folder on May 6 2017.)

On gitter it has been suggested to me to restart the node. It now syncs until block 138 in a Debian stretch VM. Then again just stops, doing nothing, no error.

**Comment by zack-bitcoin** [comment]
At that time there were only 138 blocks. Now there are more.
