### ISSUE TITLE
Mining balance reset to zero

### ISSUE THREAD

**Issue by MarkGriffin** [aeternity/testnet#74]
I have been mining and the balance has been increasing.

However, this afternoon (Monday 8 May 2017) the balance has been reset to zero. Did you reset the database?

How can I claim my original balance? 

I hope that it has not been lost.

**Comment by simonpbond** [comment]
Hi Mark,

I'm not with Aeternity, however I don't believe the balance has any value as this is only the "test" net.

However, I'm also interested to know how your balance could have got reset to zero, hopefully this would never happen in the "main" net in the future!

**Comment by zack-bitcoin** [comment]
Hi Mark,

Sorry you lost your testnet tokens.
In order to facilitate fast development we frequently restart the testnet blockchain from the first block.
The alternative is to do soft-fork updates, so the blockchain needs to be programmed for both the old and new rule sets. it is much more complicated.

Once the code is more stable I will make an announcement that testnet coins will no longer be reverted, and then they will start having a value.

**Comment by simonpbond** [comment]
Zack,

> Once the code is more stable I will make an announcement that testnet coins will no longer be reverted, and then they will start having a value.

If the "test" net blockchain doesn't revert and mining the "test" net brings value, does this mean it eventually progresses to become labeled the "main" net ? Or will the "test" net and "main" net be separate blockchains?

I'm just wondering how the value comes in to play from the "test" net.

**Comment by zack-bitcoin** [comment]
We need the testnet to have some value to verify that the oracle functions correctly.
We don't want to risk investor funds with an untested oracle.
The details of how this will be achieved haven't been settled yet with the team.
These ideas are a little complicated, it takes time.
One option is that the testnet money eventually becomes 1% of the money on the main net.
Another option is to have 2 blockchains.
or we might do something different.

**Comment by MarkGriffin** [comment]
I was concerned about the system unexpectedly loosing tokens.
However, from another post, I found that easy:sync(). fixed & resolved the problem.

It would be nice if some of our testnet tokens became mainnet tokens as a reward for helping to test/debug the system.
