### ISSUE TITLE
talk helper failed

### ISSUE THREAD

**Issue by simonpbond** [aeternity/testnet#75]
Hello,

After attempting the following tutorial:
[https://blog.aeternity.com/%C3%A6ternity-testnet-install-and-mining-6f5b8e880ab1](url)

I am receiving a lot of "talk helper failed" messages.

Can you shed some light as to what this means and the reason this happens?

Thanks

**Comment by MarkGriffin** [comment]
I'm also observing these error messages.  
It's started happening after the last update.

**Comment by tclauss** [comment]
Same log message
...
talk helper fail
talk helper fail
talk helper fail
talk error 
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
...

**Comment by tclauss** [comment]
need to execute easy:sync(). first and mine:start(). work fine... 
Is necessary to execute easy:sync() first and mine:start(). will work fine...

@zack-bitcoin, can you log a message when easy:sync(). is done ?

6> easy:sync().                 
<0.522.0>
HH < Height
trade blocks7> absorb block ["block_plus",["block",1,"neBf3XDr3z41y0En",[-6],"Vh+Pjkkcy9DjdBma",1,114868301,6452,"",2],["pow","IdZk7fcSA4/jM4LL",6177,35871588236497197788248],["trees",1,0,0,0,0,38],40370176,["neBf3XDr3z41y0En"]]
absorb block ["block_plus",["block",2,"IdZk7fcSA4/jM4LL",[-6],"Vh+Pjkkcy9DjdBma",1,114871886,6452,"",2],["pow","7ew/8oYFgnPoEe1a",6177,173301741332859720002652],["trees",1,0,0,0,0,38],80740352,["IdZk7fcSA4/jM4LL"]]

...

FHjLhc0WHp/X","PrJH54Ch+TW6qREG","a+02tqCO5R42Ncxn","yS5RiJHNfcK91TzP","p6XQH/tBtxMIS3+B","OgXS+PByaKeXn0bw","Udh4J2+npAd9EB8/","8yhE1znsailvP8Ko"]]
absorb block ["block_plus",["block",467,"EE0bV+Ea6C9CmAiJ",[-6],"BshRj8dbUlRylVCo",3,117641276,6452,"",2],["pow","+XQCfcwObIQE/Wmy",6177,476255013152943410046822],["trees",11,0,0,0,0,38],18852872192,["EE0bV+Ea6C9CmAiJ","KLsii0nP2UuNFczw","5L8Hkm6Jb3aODv4h","rsz33R6igSsKuaup","cPNdqcM9+3COncbz","8mcJTymyHUIo8tYG","0RxViBHoXLc+zBlj","Htotazz6V0+Y19Sl"]]
absorb block ["block_plus",["block",468,"+XQCfcwObIQE/Wmy",[-6],"YgqrBNhhzNvkKrFB",3,117641377,6452,"",2],["pow","nzMQph4bm3nB7vRC",6177,944779097428761766729712],["trees",13,0,0,0,0,38],18893242368,["+XQCfcwObIQE/Wmy","KIIwFHjLhc0WHp/X","bVoKpmt9pXPnq1+B","INJUUgX7d0XfeZ/P","mnwTfeMkY4CXdhCe","gPJioFXUjfACU9FO","u1vXl2YKtn3Ji+Y0","ZfhytOYAdgFhafMf"]]

7> 
7> 
7> mine:start().
start mining with 3 cores.
ok
8> FOUND A BLOCK !
absorb block ["block_plus",["block",469,"nzMQph4bm3nB7vRC",[-6],"7UWDAz12Gx30zex9",[3,"SGFHbXBLTHBCMUJWWXduV1N3"],117652447,6452,"",2],["pow","U7ALT0t5a/M9WKdb",6177,621786894446767373256495],["trees",878,0,0,0,0,38],18933612544,["nzMQph4bm3nB7vRC","EE0bV+Ea6C9CmAiJ","nVue1QpG6NsYRPdC","ZQsYaOty9jJnHvGO","pD/GCBkDVIA8CCcS","CaCumh0hp5EuTbmM","nq7Tv9kKy+9lztFf","wz0zJULfP231qdwD"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",470,"U7ALT0t5a/M9WKdb",[-6],"BRWa0gIVyi8uCQHJ",3,117652516,6452,"",2],["pow","eciCU/2Y22OpkC+5",6177,867768180536195634955926],["trees",954,0,0,0,0,38],18973982720,["U7ALT0t5a/M9WKdb","+XQCfcwObIQE/Wmy","PrJH54Ch+TW6qREG","o9Ml/E5zOh2EQwCq","qot1WNkxHu0X+QlE","v2HohTsbPKz3DlfX","7E24/pZXnlLl341v","rY4nhgKR5DiV9+vI"]]
https://github.com/aeternity/testnethttps://github.com/aeternity/testnetFOUND A BLOCK !
absorb block ["block_plus",["block",471,"eciCU/2Y22OpkC+5",[-6],"ZpXBDcDpTc3NpxdO",3,117652559,6452,"",2],["pow","skiZPU2pMVT1g2/p",6177,329886671845732252800893],["trees",988,0,0,0,0,38],19014352896,["eciCU/2Y22OpkC+5","nzMQph4bm3nB7vRC","KLsii0nP2UuNFczw","LfT7C1vbayTwf/Pt","b6eQVyu5+PIrd++x","zcgoxA3W3zqWlWAa","HBGwCYzMIM8VXABC","Xd/QLh2OP++3jbRr"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",472,"skiZPU2pMVT1g2/p",[-6],"14u2cCiodG7CrTtA",3,117652677,6452,"",2],["pow","zYiNuHE2c4NO7QAp",6177,999727879956018989089084],["trees",1088,0,0,0,0,38],19054723072,["skiZPU2pMVT1g2/p","U7ALT0t5a/M9WKdb","KIIwFHjLhc0WHp/X","xzHIstD38Lfi0yVO","mKM+Df3uKwZO1Gdb","gh5JiWW2MYYBTRap","ojfpxw1HgpAfVJJG","2K1pIB3Z7VSQYVp4"]]

**Comment by zack-bitcoin** [comment]
logging a message when easy sync is done is a good idea. @tclauss 

There is a problem where if you are mining before you have synced, it spams the server and acts as a denial of service. That is why the "talk helper failed" messages were appearing.

**Comment by simonpbond** [comment]
Got it, thanks for the clarifying. @tclauss @zack-bitcoin

**Comment by MarkGriffin** [comment]
Thanks. easy:sync(). fixed & resolved the problem.

**Comment by MarkGriffin** [comment]
I'm getting the "talk helper fail" messages again today.
I exited and re-started then ran easy:sync() and then mine:start(). The messages still appear.
How can this be fixed?

**Comment by tclauss** [comment]
@zack-bitcoin, fail again for me , also ....

**Comment by zack-bitcoin** [comment]
"talk helper fail" means the server got shut down.
In the next hard fork I am upgrading the server so that it limits how much each IP can connect.
I restarted the server, it should be working now.

**Comment by tclauss** [comment]
yep !!! @zack-bitcoin , now work fine, at the moment :-) thks. btw, dont forget to log a message when easy:sync(). is done :-)

**Comment by ByoundG** [comment]
have the same message "talk helper fail" on 2017 August the 08, try  : easy:sync().
but terminal says : ** exception error: undefined function easy:sync/0
Waiting for your kindly advice

**Comment by michalzajda** [comment]
The api changed, so this is why this call fails. Please look at the doc in docs directory. This one is good: https://github.com/aeternity/testnet/blob/master/docs/getting-started/build_intro.md

**Comment by ByoundG** [comment]
On a fresh update, from ubuntu, erlang, github,
I did : 
make prod-attach // "that answer erlang.pip.1"
syn:start(). // "ok"
keys:new("SeaArt"). //"ok"

then :
keys:pubkeys(). // ** exception exit: {noproc,{gen_server,call,[keys,pubkey]}}
     in function  gen_server:call/2 (gen_server.erl, line 204)
or : 
keys:address(). // "** exception error: undefined function keys:address/0"

Would you tell me how to create a account on the prod nod,

Obligingly,
