### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by kalleknast** [aeternity/testnet#76]
I ran the miner on the testnet and experienced a memory problem.
I think the problem is related to issue #73 . The miner stops/crashes without any error (but, I can see that the process is no longer running, although mine:is_on(). still returns go). This stop/crash occurs after 10–30 min. After the stop/crash I restart the miner through running mine:stop(). and mine:start(). But, it seems like the memory used by the previous call to mine:start(). is not released after the crash or when I afterwards run mine:stop(). . The result is that for each time I start the miner and it crashes more more and memory gets locked up. The memory wasn't even released after exiting the testnet.

**Comment by MarkGriffin** [comment]
I'm also observing this behavior.  It's happening consistently after the latest update.

**Comment by zack-bitcoin** [comment]
It seems to me that this error only happens if you run the miner without first syncing with the network.
If you try mining before you sync, then your node downloads the same blocks over and over and doesn't sync them very fast, so it overfills your memory.

**Comment by MarkGriffin** [comment]
Thanks zach. I'll see if easy:sync(). fixes & resolves the problem.
