### ISSUE TITLE
mine:start(). crash

### ISSUE THREAD

**Issue by tclauss** [aeternity/testnet#78]
Hi @zack-bitcoin , mine:start(). crash again after a while mining ... First executed easy:sync(). and the mining start correctly ...

.....

HH < Height
HH < Height
HH < Height
HH < Height
HH < Height
HH < Height
HH < Height
HH < Height
HH < Height
absorb block ["block_plus",["block",1104,"AdSzx9Jp4rXL0xle",[-6],"Iq/IXnrOXSDKptMS",2,118321629,6452,"",2],["pow","vOb3hrvwhhry4AlL",6177,452058462367862092069574],["trees",1521,0,0,0,0,38],44568674304,["AdSzx9Jp4rXL0xle","iaJH4JdECuVEUEL+","esqcPnO5OEFFEZrS","HMuc5DPEVOuXKtKC","P6bI4/4436EQ+bwO","CkeE6nPD8cQI40C7","GSRLtjrdVvWaXNlr","QkI2NiKQUruEUaDv","nw4UkozH0UPHHC9R","urEwSct/jexg0oYe"]]
HH < Height
absorb block ["block_plus",["block",1105,"vOb3hrvwhhry4AlL",[-6],"wyenCOeeyr0Np+2Z",2,118321925,6452,"",2],["pow","0taZWl11/W2Uf0ii",6177,754363489265313669179381],["trees",1523,0,0,0,0,38],44609044480,["vOb3hrvwhhry4AlL","x76Vw3EgJ1DP02I7","meXlvBFvSQjHDxIP","2ss1T7EgV+G3qwaw","cQ/hKyJFrO96b1e4","rv+hFnciLB2jeHeh","JMojxXmoV7ZUGcSr","ROjYXWFFbepksL9U","E0y3yA+6QZyBaCOt","d/oE2CwlKtKepfZ+"]]
absorb block ["block_plus",["block",1106,"0taZWl11/W2Uf0ii",[-6],"0QAETUMMr9vf1Pft",2,118322501,6452,"",2],["pow","tXX/uvoQpWiW2obu",6177,428194578916005913926377],["trees",1525,0,0,0,0,38],44649414656,["0taZWl11/W2Uf0ii","AdSzx9Jp4rXL0xle","8rsA8dqPqv9B7y0Y","D1B2NTInYzJpmIXM","HNxfCRzp16kbWSrO","aEZ9tYTABkfms5xx","mjWvl+cOD7/s2HEi","fXXkbsQaiN5ECoIx","F6hgjd2FMorWuSlW","SptxaKaRGCiDbAbw"]]
talk helper fail
talk helper fail
talk helper fail
......

talk helper fail
absorb block talk helper fail
["block_plus",["block",1107,"tXX/uvoQpWiW2obu",[-6],"V65sz2Sop9FLRDqT",2,118322747,6452,"",2],["pow","N02/+jRsi86ZgQn8",6177,277931403628756846661929],["trees",1527,0,0,0,0,38],44689784832,["tXX/uvoQpWiW2obu","vOb3hrvwhhry4AlL","gJ4iJQqqt+qDtesp","CbD7n78NvOF/LxEM","jqzHRTR88ulT2F5C","yCnzzn9hBQnxmBbK","8d1XHFPv+E2uX//j","SGO4QQ8OcaIJMxIU","DBJIWQeBBckr+qsR","5wJc+SfID12j0m+n"]]talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail

.....

talk helper fail
died!
=ERROR REPORT==== 10-May-2017::12:57:11 ===
** Generic server block_absorber terminating 
** Last message in was {'$gen_cast',
                           {doit,
                               {block_plus,
                                   {block,1108,
                                       <<55,77,191,250,52,108,139,206,153,129,
                                         9,252>>,
                                       [],
                                       <<189,19,122,54,74,220,114,231,215,135,
                                         53,8>>,
                                       2,118323222,6452,<<>>,2},
                                   {pow,
                                       <<9,245,146,233,197,41,99,121,168,107,
                                         133,110>>,
                                       6177,508882365674028326827854},
                                   {trees,1529,0,0,0,0,38},
                                   44730155008,
                                   {'N02/+jRsi86ZgQn8',
                                       <<210,214,153,90,93,117,253,109,148,127,
                                         72,162>>,
                                       <<137,162,71,224,151,68,10,229,68,80,66,
                                         254>>,
                                       <<10,127,23,160,95,124,72,84,155,163,
                                         184,187>>,
                                       <<119,208,147,95,130,117,217,3,142,197,
                                         56,251>>,
                                       <<123,47,246,190,227,120,152,98,53,190,
                                         76,182>>,
                                       <<160,156,202,216,118,191,155,233,234,
                                         172,138,23>>,
                                       <<56,148,250,219,255,164,32,132,192,145,
                                         110,224>>,
                                       <<195,190,42,111,103,217,142,95,109,71,
                                         51,9>>,
                                       <<170,6,247,63,157,244,43,134,155,
                                         14,18,172>>}}}}
** When Server state == []
** Reason for termination == 
** {badarg,[{zlib,uncompress,1,[]},
            {block,read,1,[{file,"src/consensus/chain/block.erl"},{line,353}]},
            {block,block_times,2,
                   [{file,"src/consensus/chain/block.erl"},{line,337}]},
            {block,block_times,2,
                   [{file,"src/consensus/chain/block.erl"},{line,341}]},
            {block,median_last,2,
                   [{file,"src/consensus/chain/block.erl"},{line,332}]},
            {block,check2,1,
                   [{file,"src/consensus/chain/block.erl"},{line,308}]},
            {block_absorber,absorb,1,
                            [{file,"src/consensus/chain/block_absorber.erl"},
                             {line,33}]},
            {block_absorber,handle_cast,2,
                            [{file,"src/consensus/chain/block_absorber.erl"},
                             {line,15}]}]}
talk helper fail
talk helper fail

=ERROR REPORT==== 10-May-2017::12:57:11 ===
File operation error: emfile. Target: /usr/lib/erlang/lib/stdlib-3.2/ebin/sys.beam. Function: get_file. Process: code_server.
talk helper fail

......

died!
=ERROR REPORT==== 10-May-2017::12:58:02 ===
** Generic server block_absorber terminating 
** Last message in was {'$gen_cast',
                           {doit,
                               {block_plus,
                                   {block,1135,
                                       <<235,200,14,220,192,219,173,187,237,86,
                                         89,195>>,
                                       [],
                                       <<139,49,67,25,128,117,60,122,20,92,106,
                                         223>>,
                                       2,118331287,6452,<<>>,2},
                                   {pow,
                                       <<9,122,19,174,166,208,182,22,42,81,80,
                                         59>>,
                                       6177,384819953478737732885013},
                                   {trees,1583,0,0,0,0,38},
                                   45820149760,
                                   {'68gO3MDbrbvtVlnD',
                                       <<11,250,66,51,116,127,152,112,16,26,24,
                                         233>>,
                                       <<231,201,133,248,52,174,101,55,172,133,
                                         21,19>>,
                                       <<215,122,218,78,76,106,162,92,9,33,1,93>>,
                                       <<188,230,247,134,187,240,134,26,242,
                                         224,9,75>>,
                                       <<11,95,4,159,142,136,121,44,8,195,213,
                                         39>>,
                                       <<162,202,181,103,18,136,149,93,246,93,
                                         92,71>>,
                                       <<248,164,61,14,171,86,242,253,111,142,
                                         6,238>>,
                                       <<179,227,127,30,79,221,7,214,106,140,
                                         172,211>>,
                                       <<91,156,200,47,57,167,79,15,128,
                                         102,112,61>>}}}}
** When Server state == []
** Reason for termination == 
** {{badrecord,block_plus},
    [{block,check2,1,[{file,"src/consensus/chain/block.erl"},{line,288}]},
     {block_absorber,absorb,1,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,33}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,15}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
absorb block ["block_plus",["block",1136,"CXoTrqbQthYqUVA7",[-6],"cI5MJbRIKpBumWwD",2,118331874,6452,"",2],["pow","OsjY6XfIphXwvN8o",6177,809526197802101125563056],["trees",1585,0,0,0,0,38],45860519936,["CXoTrqbQthYqUVA7","iS4JEe2bPQHuAV9J","E8oEnukvMWhtyd/3","0zzDWILb00dKznzF","0taZWl11/W2Uf0ii","P6bI4/4436EQ+bwO","KquM937+5/qA6jnC","e0f+zU7mFcQ0SUhF","pNxE4aHg2GpxI4cr","c0BvedxaVrSKxWqA"]]
died!
=ERROR REPORT==== 10-May-2017::12:58:02 ===
** Generic server block_absorber terminating 
** Last message in was {'$gen_cast',
                           {doit,
                               {block_plus,
                                   {block,1136,
                                       <<9,122,19,174,166,208,182,22,42,81,80,
                                         59>>,
                                       [],
                                       <<112,142,76,37,180,72,42,144,110,153,
                                         108,3>>,
                                       2,118331874,6452,<<>>,2},
                                   {pow,
                                       <<58,200,216,233,119,200,166,21,240,188,
                                         223,40>>,
                                       6177,809526197802101125563056},
                                   {trees,1585,0,0,0,0,38},
                                   45860519936,
                                   {'CXoTrqbQthYqUVA7',
                                       <<137,46,9,17,237,155,61,1,238,1,95,73>>,
                                       <<19,202,4,158,233,47,49,104,109,201,
                                         223,247>>,
                                       <<211,60,195,88,130,219,211,71,74,206,
                                         124,197>>,
                                       <<210,214,153,90,93,117,253,109,148,127,
                                         72,162>>,
                                       <<63,166,200,227,254,56,223,161,16,249,
                                         188,14>>,
                                       <<42,171,140,247,126,254,231,250,128,
                                         234,57,194>>,
                                       <<123,71,254,205,78,230,21,196,52,73,72,
                                         69>>,
                                       <<164,220,68,225,161,224,216,106,113,35,
                                         135,43>>,
                                       <<115,64,111,121,220,90,86,180,138,
                                         197,106,128>>}}}}
** When Server state == []
** Reason for termination == 
** {{badrecord,block_plus},
    [{block,check2,1,[{file,"src/consensus/chain/block.erl"},{line,288}]},
     {block_absorber,absorb,1,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,33}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,15}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
absorb block ["block_plus",["block",1137,"OsjY6XfIphXwvN8o",[-6],"8VcHhvKd8lscjQYy",2,118332003,6452,"",2],["pow","Zfn/eerSAc/GamOw",6177,453895032867226665331051],["trees",1587,0,0,0,0,38],45900890112,["OsjY6XfIphXwvN8o","68gO3MDbrbvtVlnD","AU00lwA4mECoNDCY","aafNF7bV2bbD+1c+","tXX/uvoQpWiW2obu","cQ/hKyJFrO96b1e4","ez9NOD+gxtcJyo2p","x0fh7wWOQkE06Am9","h69SYjNBk2t4wVnn","zrRrZAq9ySPEmsWO"]]
died!
=ERROR REPORT==== 10-May-2017::12:58:02 ===
** Generic server block_absorber terminating 
** Last message in was {'$gen_cast',
                           {doit,
                               {block_plus,
                                   {block,1137,
                                       <<58,200,216,233,119,200,166,21,240,188,
                                         223,40>>,
                                       [],
                                       <<241,87,7,134,242,157,242,91,28,141,6,
                                         50>>,
                                       2,118332003,6452,<<>>,2},
                                   {pow,
                                       <<101,249,255,121,234,210,1,207,198,106,
                                         99,176>>,
                                       6177,453895032867226665331051},
                                   {trees,1587,0,0,0,0,38},
                                   45900890112,
                                   {'OsjY6XfIphXwvN8o',
                                       <<235,200,14,220,192,219,173,187,237,86,
                                         89,195>>,
                                       <<1,77,52,151,0,56,152,64,168,52,48,152>>,
                                       <<105,167,205,23,182,213,217,182,195,
                                         251,87,62>>,
                                       <<181,117,255,186,250,16,165,104,150,
                                         218,134,238>>,
                                       <<113,15,225,43,34,69,172,239,122,111,
                                         87,184>>,
                                       <<123,63,77,56,63,160,198,215,9,202,141,
                                         169>>,
                                       <<199,71,225,239,5,142,66,65,52,232,9,
                                         189>>,
                                       <<135,175,82,98,51,65,147,107,120,193,
                                         89,231>>,
                                       <<206,180,107,100,10,189,201,35,196,
                                         154,197,142>>}}}}
** When Server state == []
** Reason for termination == 
** {{badrecord,block_plus},
    [{block,check2,1,[{file,"src/consensus/chain/block.erl"},{line,288}]},
     {block_absorber,absorb,1,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,33}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,15}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
absorb block ["block_plus",["block",1138,"Zfn/eerSAc/GamOw",[-6],"jhRXAYwOW9FDHpE+",2,118332030,6452,"",2],["pow","AwEruWo32lcaDbqW",6177,142945158170370177059982],["trees",1589,0,0,0,0,38],45941260288,["Zfn/eerSAc/GamOw","CXoTrqbQthYqUVA7","WFyz3U3lDcd1m8kf","3N8ZzfXYn8UjxEmg","N02/+jRsi86ZgQn8","HNxfCRzp16kbWSrO","16QNJmA/4ZAq+3cG","kJSyYZmTg08ARDCe","8o4fACd3DW7CG0Ss","luLmIGV6S5/uVLeN"]]
died!
=ERROR REPORT==== 10-May-2017::12:58:02 ===
** Generic server block_absorber terminating 
** Last message in was {'$gen_cast',
                           {doit,
                               {block_plus,
                                   {block,1138,
                                       <<101,249,255,121,234,210,1,207,198,106,
                                         99,176>>,
                                       [],
                                       <<142,20,87,1,140,14,91,209,67,30,145,62>>,
                                       2,118332030,6452,<<>>,2},
                                   {pow,
                                       <<3,1,43,185,106,55,218,87,26,13,186,150>>,
                                       6177,142945158170370177059982},
                                   {trees,1589,0,0,0,0,38},
                                   45941260288,
                                   {'Zfn/eerSAc/GamOw',
                                       <<9,122,19,174,166,208,182,22,42,81,80,
                                         59>>,
                                       <<88,92,179,221,77,229,13,199,117,155,
                                         201,31>>,
                                       <<220,223,25,205,245,216,159,197,35,196,
                                         73,160>>,
                                       <<55,77,191,250,52,108,139,206,153,129,
                                         9,252>>,
                                       <<28,220,95,9,28,233,215,169,27,89,42,
                                         206>>,
                                       <<215,164,13,38,96,63,225,144,42,251,
                                         119,6>>,
                                       <<144,148,178,97,153,147,131,79,0,68,48,
                                         158>>,
                                       <<242,142,31,0,39,119,13,110,194,27,68,
                                         172>>,
                                       <<150,226,230,32,101,122,75,159,238,
                                         84,183,141>>}}}}
** When Server state == []
** Reason for termination == 
** {{badrecord,block_plus},
    [{block,check2,1,[{file,"src/consensus/chain/block.erl"},{line,288}]},
     {block_absorber,absorb,1,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,33}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,15}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
absorb block ["block_plus",["block",1139,"AwEruWo32lcaDbqW",[-6],"uZEUuwx8F+DVFJSV",2,118332065,6452,"",2],["pow","fTQxGBRLAk/Xax89",6177,325594499199846961339557],["trees",1591,0,0,0,0,38],45981630464,["AwEruWo32lcaDbqW","OsjY6XfIphXwvN8o","C/pCM3R/mHAQGhjp","tDmHO3Tr52HyNpIU","CfWS6cUpY3moa4Vu","jqzHRTR88ulT2F5C","Mw/aN8QL9298AX3F","YjEQukHOoYc2wBJl","C6J38QGa4N4AKO/0","sp3j42RYcA2eB1Be"]]
died!
=ERROR REPORT==== 10-May-2017::12:58:02 ===
** Generic server block_absorber terminating 
** Last message in was {'$gen_cast',
                           {doit,
                               {block_plus,
                                   {block,1139,
                                       <<3,1,43,185,106,55,218,87,26,13,186,150>>,
                                       [],
                                       <<185,145,20,187,12,124,23,224,213,20,
                                         148,149>>,
                                       2,118332065,6452,<<>>,2},
                                   {pow,
                                       <<125,52,49,24,20,75,2,79,215,107,31,61>>,
                                       6177,325594499199846961339557},
                                   {trees,1591,0,0,0,0,38},
                                   45981630464,
                                   {'AwEruWo32lcaDbqW',
                                       <<58,200,216,233,119,200,166,21,240,188,
                                         223,40>>,
                                       <<11,250,66,51,116,127,152,112,16,26,24,
                                         233>>,
                                       <<180,57,135,59,116,235,231,97,242,54,
                                         146,20>>,
                                       <<9,245,146,233,197,41,99,121,168,107,
                                         133,110>>,
                                       <<142,172,199,69,52,124,242,233,83,216,
                                         94,66>>,
                                       <<51,15,218,55,196,11,247,111,124,1,125,
                                         197>>,
                                       <<98,49,16,186,65,206,161,135,54,192,18,
                                         101>>,
                                       <<11,162,119,241,1,154,224,222,0,40,239,
                                         244>>,
                                       <<178,157,227,227,100,88,112,13,158,
                                         7,80,94>>}}}}
** When Server state == []
** Reason for termination == 
** {{badrecord,block_plus},
    [{block,check2,1,[{file,"src/consensus/chain/block.erl"},{line,288}]},
     {block_absorber,absorb,1,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,33}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,15}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

**Comment by kalleknast** [comment]
Same for me, but somewhat different errors.
I let easy:sync(). run until it seemed to be synced (height 1363), and then started mining. The mining worked ok for a while and then sent a few Error Reports, and after yet another 10 min it starts to print 
"talk error"  and "talk helper fail". But it kept finding blocks for ~40 min until it stopped/crashed without any error message (at height 1520).

**Comment by zack-bitcoin** [comment]
Thanks for the error reports.

The miner is set up to sync blocks with the server occasionally. It seems like on some computers these processes for syncing with the server aren't dying, they keep increasing in number until the node crashes.

**Comment by kalleknast** [comment]
Is there anything we can do to help you find the problem?

**Comment by tclauss** [comment]
@zack-bitcoin, now seems to work fine mine:start(). a bit more late i will test again it !


testnet@aeternity:~/testnet$ sh start.sh
From https://github.com/aeternity/testnet
 * branch            master     -> FETCH_HEAD
Already up-to-date.
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:3:3] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.2.1  (abort with ^G)
1> start keys
start toptx pool started
start server
easy:sync().
<0.416.0>
HH < Height
trade blocks2> absorb block ["block_plus",["block",1,"neBf3XDr3z41y0En",[-6],"Vh+Pjkkcy9DjdBma",1,114868301,6452,"",2],["pow","IdZk7fcSA4/jM4LL",6177,35871588236497197788248],["trees",1,0,0,0,0,38],40370176,["neBf3XDr3z41y0En"]]
absorb block ["block_plus",["block",2,"IdZk7fcSA4/jM4LL",[-6],"Vh+Pjkkcy9DjdBma",1,114871886,6452,"",2],["pow","7ew/8oYFgnPoEe1a",6177,173301741332859720002652],["trees",1,0,0,0,0,38],80740352,["IdZk7fcSA4/jM4LL"]]
absorb block ["block_plus",["block",3,"7ew/8oYFgnPoEe1a",[-6],"Vh+Pjkkcy9DjdBma",1,114872185,6452,"",2],["pow","AE/73wrXLd2s4yxR",6177,483028171846200657419870],["trees",1,0,0,0,0,38],121110528,["7ew/8oYFgnPoEe1a"]]

.........



absorb block ["block_plus",["block",1430,"YumIQDpY3IykBLsu",[-6],"NtOZa5gIHdPBc3UC",4,119446378,6452,"",2],["pow","Cx5WruyQ5sPUEKL+",6177,464740020641414539192524],["trees",11,0,0,0,0,38],57729351680,["YumIQDpY3IykBLsu","dmJK1lRsl+Om+XMC","r+IUg8L+F+jgSHKV","uMbRJWZSS11tftHM","J6UeogztGSSWtHsQ","UjvVJEfheOw1K7kV","5qM6ALO5RMhydMUT","chrzy/IgTcywtYzb","fWqT6JStsBP0vfKz","v2HohTsbPKz3DlfX"]]
  
2> 
2> mine:start().  
start mining with 3 cores.
ok
3> FOUND A BLOCK !
absorb block ["block_plus",["block",1431,"Cx5WruyQ5sPUEKL+",[-6],"kqXPKNDN2QamrJBO",[4,"R2JZeXRFekI1cEQzZjhGd0Nz"],119462142,6452,"",2],["pow","SlRqwSuUY7dCMBxx",6177,302473687156709329672875],["trees",2989,0,0,0,0,38],57769721856,["Cx5WruyQ5sPUEKL+","y4tHkl9QMsqnf4m6","mSURrNF5ROKk9krf","XePSi7+MD28JCTwy","YI6FZn1CCgGDtwPD","z84Zp9osNzaJK0pJ","ZA8RbQbNsNFvOYnr","lgp6KA5p6oTyxaW+","gSDYS5F8v9D+llUt","zcgoxA3W3zqWlWAa"]]

......

**Comment by tclauss** [comment]
@zack-bitcoin .... finally mining crash again :-(


FOUND A BLOCK !
absorb block ["block_plus",["block",1469,"IDg0N83xtfaB2eUn",[-6],"Dgjd0uQagXQ3F+mK",4,119469745,6452,"",2],["pow","CHvHW0Ibd+Th21QI",6177,656590426883241570450808],["trees",9186,0,0,0,0,38],59303788544,["IDg0N83xtfaB2eUn","J86pWOZ3sg/2KzNJ","gCckqe25nVPzeJpH","2zVwsmvfTlFQdNyo","+SqlATIqROEYZz59","0JiJgkPEVTgUplEQ","YhFC7bV2E8nIExiP","1STYZNJUM9Wzk33a","I3RqpH0zWC4QKh4y","Br/yiuBPXGl88H0Q"]]
talk helper fail
talk helper fail
talk helper fail
talk helper fail

....


=ERROR REPORT==== 11-May-2017::18:59:28 ===
Error in process <0.5250.2> with exit value:
{badarg,[{zlib,uncompress,1,[]},
         {block,read,1,[{file,"src/consensus/chain/block.erl"},{line,353}]},
         {easy,sync2,2,[{file,"src/easy.erl"},{line,20}]}]}

=ERROR REPORT==== 11-May-2017::18:59:28 ===
Error in process <0.5251.2> with exit value:
{badarg,[{zlib,uncompress,1,[]},
         {block,read,1,[{file,"src/consensus/chain/block.erl"},{line,353}]},
         {easy,sync2,2,[{file,"src/easy.erl"},{line,20}]}]}

=ERROR REPORT==== 11-May-2017::18:59:28 ===
Error in process <0.5134.2> with exit value:
{badarg,[{zlib,uncompress,1,[]},
         {block,read,1,[{file,"src/consensus/chain/block.erl"},{line,353}]},
         {easy,sync2,2,[{file,"src/easy.erl"},{line,20}]}]}
talk helper fail

=ERROR REPORT==== 11-May-2017::18:59:28 ===
Error in process <0.5149.2> with exit value:
{badarg,[{zlib,uncompress,1,[]},
         {block,read,1,[{file,"src/consensus/chain/block.erl"},{line,353}]},
         {easy,sync2,2,[{file,"src/easy.erl"},{line,20}]}]}

=ERROR REPORT==== 11-May-2017::18:59:28 ===
Error in process <0.5150.2> with exit value:
{badarg,[{zlib,uncompress,1,[]},
         {block,read,1,[{file,"src/consensus/chain/block.erl"},{line,353}]},
         {easy,sync2,2,[{file,"src/easy.erl"},{line,20}]}]}
talk helper fail

=ERROR REPORT==== 11-May-2017::18:59:28 ===
Error in process <0.5861.2> with exit value:
{badarg,[{zlib,uncompress,1,[]},
         {block,read,1,[{file,"src/consensus/chain/block.erl"},{line,353}]},
         {easy,height,0,[{file,"src/easy.erl"},{line,9}]},
         {easy,sync3,0,[{file,"src/easy.erl"},{line,12}]}]}
talk helper fail

=ERROR REPORT==== 11-May-2017::18:59:28 ===
Error in process <0.5862.2> with exit value:
{badarg,[{zlib,uncompress,1,[]},
         {block,read,1,[{file,"src/consensus/chain/block.erl"},{line,353}]},
         {easy,height,0,[{file,"src/easy.erl"},{line,9}]},
         {easy,sync3,0,[{file,"src/easy.erl"},{line,12}]}]}

=ERROR REPORT==== 11-May-2017::18:59:28 ===
Error in process <0.5863.2> with exit value:
{badarg,[{zlib,uncompress,1,[]},
         {block,read,1,[{file,"src/consensus/chain/block.erl"},{line,353}]},
         {easy,height,0,[{file,"src/easy.erl"},{line,9}]},
         {easy,sync3,0,[{file,"src/easy.erl"},{line,12}]}]}

.....

talk error 
talk helper fail
talk error 
talk helper fail
talk error 
talk helper fail
talk error 
talk helper fail
talk error 
talk helper fail
talk error 
talk helper fail
talk error 
talk helper fail
talk helper fail
talk error 
talk helper fail
talk error 
talk helper fail
talk helper fail
talk helper fail
talk error

**Comment by zack-bitcoin** [comment]
I made a gen_server for syncing, so these problems should go away after the next hard fork.
It seems like the old way of syncing ended up starting too many processes at once, and they were all reading from files at once too which causes problems, especially on mac.

**Comment by tclauss** [comment]
@zack-bitcoin, any news ? now i get easy:sync() issues ...

talk helper fail
talk error

**Comment by zack-bitcoin** [comment]
The old way of syncing had many issues.
I wrote a new way of syncing into the next version of the blockchain. 
In the next few days we will restart from block 0 again, and then syncing will work well.

**Comment by dushan07** [comment]
Hey Zack, 
I got up to absorb block: 3199 After that all I get is  "talk helper fail"

**Comment by zack-bitcoin** [comment]
@dushan07 the server crashed around the time you made that comment.
I fixed the bug and restarted the server, so it should work now.

**Comment by dushan07** [comment]
thanks Zack
