### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by MarkGriffin** [aeternity/testnet#79]
Is there is a memory leak that needs to be fixed?

FOUND A BLOCK !
absorb block ["block_plus",["block",1555,"uFv4x+ps2Pwt9cO1",[-6],"X4TRJHB2PSsXsUdZ",2,119562294,6452,"",2],["pow","FvegaGHEsI4AlBj3",6177,639530286632174285858182],["trees",10098,0,0,0,0,38],62775623680,["uFv4x+ps2Pwt9cO1","niNV00cKXRy+kqEu","e+FN8X388dQUsFoA","vkKvuP0INAR0ASl+","HLii1e0K51+FB+eH","9ehL7hxvV61CCyHY","y4tHkl9QMsqnf4m6","XabmAkh2+cWZCeh6","yCnzzn9hBQnxmBbK","DY3OhR37iJcs6GFE"]]
**Segmentation fault (core dumped)**
mark:~/testnet$

**Comment by zack-bitcoin** [comment]
How much RAM does your system have?

I haven't set up the merkel trees to garbage collect yet, maybe it is because of them.

**Comment by MarkGriffin** [comment]
Hi Zack, 
6GB. There seems to be plenty of memory free:
memsup:get_system_memory_data().
[{system_total_memory,6391386112},
 {free_swap,1043042304},
 {total_swap,1073741824},
 {cached_memory,193101824},
 {buffered_memory,34848768},
 {free_memory,3567591424},
 {total_memory,6391386112}]

**Comment by zack-bitcoin** [comment]
A memory leak was solved for the next time we restart the testnet.
but the error looked different on my machine.
