### ISSUE TITLE
block 312 duplicado

### ISSUE THREAD

**Issue by bilbma** [aeternity/testnet#82]
HH < Height
FOUND A BLOCK !
absorb block ["block_plus",["block",312,"tX2q79G21Dyb4UWc",[-6],"X/DBcwy0W/URKrME",3,122007775,6452,"",2],["pow","6PJ0//rqwXMI1BN0",6177,709235033936472196857624],["trees",7473,0,0,0,0,38],12595494912,["tX2q79G21Dyb4UWc","1+RueX5AIM/95Lby","li9CDZcznSHZKgnO","ML3an5Kv1ysnx0AY","7wRvVlD2k3hqVfK/","vRBuRdGwZ+uUi12T","npKQr0ItMA/hZUCy","Hld6+9UZHaDgWLo4"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",312,"tX2q79G21Dyb4UWc",[-6],"X/DBcwy0W/URKrME",3,122007794,6452,"",2],["pow","YCtgTMKHJ1YHsjOP",6177,724334958497175532547777],["trees",7484,0,0,0,0,38],12595494912,["tX2q79G21Dyb4UWc","1+RueX5AIM/95Lby","li9CDZcznSHZKgnO","ML3an5Kv1ysnx0AY","7wRvVlD2k3hqVfK/","vRBuRdGwZ+uUi12T","npKQr0ItMA/hZUCy","Hld6+9UZHaDgWLo4"]]
HH < Height

**Comment by zack-bitcoin** [comment]
the difficulty is very low. If your computer has multiple processors, and they both find a block at the same time, then this is what it looks like.
Si tienes un computadora con mas de uno CPU, esto pasa. no hay problema.
