### ISSUE TITLE
review Whitepaper Indonesia and add to aeternity website

### ISSUE THREAD

**Issue by adrelanos** [aeternity/testnet#84]
TODO:

* review (that it's accurate, human translation, not translated using google translate)
* add to aeternity website (since still hosted at the user's google drive account which could go down at some point)

Resources:

* https://drive.google.com/file/d/0B-B_AhuJ3i10dkVwcGxpTHhhNEE/view
* https://github.com/aeternity/wiki/wiki/Whitepaper_Indonesia

**Comment by bb2ebb** [comment]
an original source of whitepaper in indonesia language : https://drive.google.com/open?id=0B-B_AhuJ3i10LURNUEpKZEdLRm8 (doc format) ;)

**Comment by adrelanos** [comment]
It's the same person.

@bb2ebb on github is [fitraok09](https://bitcointalk.org/index.php?action=profile;u=352642) who did as far I know the first and only Indonesian white paper.

* https://bitcointalk.org/index.php?topic=1899109.msg18988091#msg18988091
* https://bitcointalk.org/index.php?topic=1899109.msg19218824#msg19218824

**Comment by zack-bitcoin** [comment]
This isn't the github repository for the white paper. 
Do this stuff here: https://github.com/aeternity/whitepaper
