### ISSUE TITLE
mining  with unlock keys but no balance

### ISSUE THREAD

**Issue by bilbma** [aeternity/testnet#85]
18> keys:address().
<<"FnEVGomckbqQAyN8aZ">>
19> FOUND A BLOCK !
absorb block ["block_plus",["block",1842,"AYElQcnK0tXeJ9pB",[-6],"MwQYlHvxA2yD1sZN",6,123536949,6452,"",2],["pow","5BHEVCkG+R9uxReB",6177,937319610985897724837852],["trees",10299,0,0,0,0,38],74361864192,["AYElQcnK0tXeJ9pB","8737BDS6gy9nvXqk","VrBzK5UW6aQ9b2Lv","zxGvek7Xsiy5phh0","oZFNDe6V0k9eB1dm","3qF01sK4OrMQMBRf","yXSfhHDOmZsdbnVr","WFvtMgNnG9iwVUaW","2w2+6Sob3GF/mWU9","CTixM9ReSB1pAoQJ"]]
key
19> keys:adrress().
* 2: syntax error before: keys
19> keys:adrress().
** exception error: undefined function keys:adrress/0
20> keys:adrress().                                    
** exception error: undefined function keys:adrress/0
21> keys:adrress().
** exception error: undefined function keys:adrress/0
22> keys:address().
<<"FnEVGomckbqQAyN8aZ">>
23> easy:balance().
this account does not yet exist
["0.00000000"]
24> FOUND A BLOCK !
absorb block ["block_plus",["block",1843,"5BHEVCkG+R9uxReB",[-6],"QGv/VrGUVlbYpt2H",6,123540153,6452,"",2],["pow","egrLNnj00zW3SGDp",6177,313256254004658244826492],["trees",11553,0,0,0,0,38],74402234368,["5BHEVCkG+R9uxReB","r8eSJff8cq1yOISe","OMoleFOxTKMx7jmb","QQ7s+EqESQSmGi5p","kykVD7yrW+15Pi5M","gW05QDkorVA5vG54","ywmuWnzn8GokhN0+","3xIQ4O+3geBJSbF8","/ec1HeoJxDsfRSSP","doOx+kkUegmibJsw"]]

24> keys:unlock("").
ok
25> easy:balance().
this account does not yet exist
["0.00000000"]
26> FOUND A BLOCK !
absorb block ["block_plus",["block",1844,"egrLNnj00zW3SGDp",[-6],"vnajwut+d25MUBUL",6,123541442,6452,"",2],["pow","w0WktTeBpowjXOQ/",6177,138401037531026298440618],["trees",12065,0,0,0,0,38],74442604544,["egrLNnj00zW3SGDp","AYElQcnK0tXeJ9pB","mPIOCqdrj/0jg3o9","dRPqs8VtBC5IQDRv","o6hlnVWiNZMhlE1C","I9oOCBodKcCYZYXB","Xs5MGb6HFY33ieb4","+tcfH5KH851JjCSe","zIGOPTFoge3y2OqZ","pMctYwpoBFfGfFr8"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1845,"w0WktTeBpowjXOQ/",[-6],"M+JVF2pm249PnEAN",6,123542804,6452,"",2],["pow","EJfvGoehD1U0JfjR",6177,709914362286577208492784],["trees",12573,0,0,0,0,38],74482974720,["w0WktTeBpowjXOQ/","5BHEVCkG+R9uxReB","ub+N3nrCE84jqpBB","dE9SSrAesY5KQHow","AVv4Dr49NhFJs/8K","v/IxhoTZBJ5lragy","Y6iukAHkXvhT+owi","X4nNWhZonFsvuInL","eLbVQGG0GgjZWhLr","lmgV+C6mjoRohnra"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1846,"EJfvGoehD1U0JfjR",[-6],"ACwr3DjXIdAgyc00",6,123542867,6452,"",2],["pow","MkUdJldWKAVQM5U7",6177,817951669051302522937881],["trees",12597,0,0,0,0,38],74523344896,["EJfvGoehD1U0JfjR","egrLNnj00zW3SGDp","8737BDS6gy9nvXqk","lFrT9LMV8t7ZH+wj","ihNWUljUUf1gUqwb","/16t7hEV2XhFZSwV","v140JxoQcI8AO/6R","bqEra2LbGASvSiCa","orvoWwkEd4rarPKr","Su7PT5AFmEv3SY6G"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1847,"MkUdJldWKAVQM5U7",[-6],"AWh0GhYcqEjzSIg+",6,123544475,6452,"",2],["pow","R3+JXUx1vbJ39j1+",6177,965719620771241579950532],["trees",13153,0,0,0,0,38],74563715072,["MkUdJldWKAVQM5U7","w0WktTeBpowjXOQ/","r8eSJff8cq1yOISe","pAhcNRCJi4TwVz2D","ZRoQpmrETX9F1Qev","nyNSTppNvM20Gd4f","LmsuFtF7eI7Qt4SJ","jsl5k5ZHyDTWuXtD","nMX1NjXL2E+63qHW","6g7KPQVDovI7qqEn"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1848,"R3+JXUx1vbJ39j1+",[-6],"R+/1Kum7jt1fDVo6",6,123544723,6452,"",2],["pow","eefUSYqSKz9CiDbi",6177,378772252493325514790854],["trees",13247,0,0,0,0,38],74604085248,["R3+JXUx1vbJ39j1+","EJfvGoehD1U0JfjR","AYElQcnK0tXeJ9pB","wbMY4RHWh2/7nH4/","rUYPiiy22FmRZtBx","oFww0cgYPvz6T1aM","avBm7JQxP/ZFKTbb","9YnBIcTKi7Tg3ESJ","i+z4ygtMe/PCH5bU","fzjj4K4/WdOt8EDm"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1849,"eefUSYqSKz9CiDbi",[-6],"N+eWeMRkBKY1e0aZ",6,123545159,6452,"",2],["pow","LOxvbqmqvriyiKOI",6177,597940008219907509491661],["trees",13405,0,0,0,0,38],74644455424,["eefUSYqSKz9CiDbi","MkUdJldWKAVQM5U7","5BHEVCkG+R9uxReB","xuMbRcPQRvUN6lYx","BctKvDieaxmjVPd8","FRyZWI9CZqLJ5PB8","Z4391oXW45odb/eu","VrOgETvbtQ+j5C9b","psITfbcz0Ws+Wr5h","ufInFAVYoVlbo5ie"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1850,"LOxvbqmqvriyiKOI",[-6],"udEIUZh0ceOTGcA0",6,123546260,6452,"",2],["pow","g6VwJtCspMyhapNh",6177,517843336689826012139812],["trees",13819,0,0,0,0,38],74684825600,["LOxvbqmqvriyiKOI","R3+JXUx1vbJ39j1+","egrLNnj00zW3SGDp","VrBzK5UW6aQ9b2Lv","/CSz4z0WUc0zGT2r","5wkIksmO+MrmzY1R","v3chZNdnsSQBYQav","0Wn4NQS7Z0JdDa5Y","XJ74AhpOKn87TZSU","EywUMOsdqpo46L/i"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1851,"g6VwJtCspMyhapNh",[-6],"9uqu4us5yNYHlTXG",6,123546458,6452,"",2],["pow","B2tuEdtqY8DD0BEu",6177,186429202656870943885344],["trees",13903,0,0,0,0,38],74725195776,["g6VwJtCspMyhapNh","eefUSYqSKz9CiDbi","w0WktTeBpowjXOQ/","OMoleFOxTKMx7jmb","auwEq1i7nCUgVgVL","gUbM059YHTOX5ySP","DQgXDR2C3YTjQb/P","ZOLuIZm0R9PPK4qi","8fs1WngIIEkGpl/o","olP1I/+a1udIQDox"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1852,"B2tuEdtqY8DD0BEu",[-6],"nVT+eODoAk6TP4ae",6,123549046,6452,"",2],["pow","Yk8KMhiWcYIIDj9H",6177,25300168670057004973910],["trees",14959,0,0,0,0,38],74765565952,["B2tuEdtqY8DD0BEu","LOxvbqmqvriyiKOI","EJfvGoehD1U0JfjR","mPIOCqdrj/0jg3o9","LYrigKhypMC9Mf/B","+fF3OV3i5n7S3KJW","pkBoypsfBXGXB6g2","LyRQXRetlE8BErdr","6NlDn/calBa3xQ7h","rHaIdgSJSf9SZuSq"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1853,"Yk8KMhiWcYIIDj9H",[-6],"f28obYSHIf0UcFwG",6,123549538,6452,"",2],["pow","ctFTVqq7qvxrX7Mi",6177,481467435616169052334246],["trees",15163,0,0,0,0,38],74805936128,["Yk8KMhiWcYIIDj9H","g6VwJtCspMyhapNh","MkUdJldWKAVQM5U7","ub+N3nrCE84jqpBB","wgVf3hzuqsIl2A9d","7+uYSldy6qu+btw5","aAkNzIa+T6F26sCS","wT+/U7HQHsQAo5oI","YhFC7bV2E8nIExiP","/+Oh7h4gnwrGFZxG"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1854,"ctFTVqq7qvxrX7Mi",[-6],"aD25jt3uBUxQFXmd",6,123550427,6452,"",2],["pow","JVJmsyn7iAbbzY55",6177,846652615383455199650329],["trees",15505,0,0,0,0,38],74846306304,["ctFTVqq7qvxrX7Mi","B2tuEdtqY8DD0BEu","R3+JXUx1vbJ39j1+","8737BDS6gy9nvXqk","4M43yA3fqHOa2eJx","IU/uLVCc0HwZleWy","DPklEp8WMyJ2grvL","aLfIJ5fYHHmFBAqU","3nqhGhoXHRY5oVCm","jCXv+C5urw/7uLNA"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1855,"JVJmsyn7iAbbzY55",[-6],"5ha9RjnIurPsaS/A",6,123550477,6452,"",2],["pow","FwYjnSsx1Ka07eBf",6177,971055947264301487375734],["trees",15525,0,0,0,0,38],74886676480,["JVJmsyn7iAbbzY55","Yk8KMhiWcYIIDj9H","eefUSYqSKz9CiDbi","r8eSJff8cq1yOISe","44M3dNUrIHduQsQx","xV1lEd2PjTSAN1P3","hccF0sNsxuuhzKVl","z3OsfkftjWkWpubP","MuK7VP8VT/Mz7VXi","tV9FzEEXPSVrNdUj"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1856,"FwYjnSsx1Ka07eBf",[-6],"uFcx69072ZRHdhlR",6,123553247,6452,"",2],["pow","5ibyd2sy6mX9LCEt",6177,888263408776998756486770],["trees",16637,0,0,0,0,38],74927046656,["FwYjnSsx1Ka07eBf","ctFTVqq7qvxrX7Mi","LOxvbqmqvriyiKOI","AYElQcnK0tXeJ9pB","3c24gKAj6nBJr5Wy","C/2dnpN8v0gdyWgF","J8p6ejT3gam7Rmxg","3UOV+4UxJgPVsT+T","6BTvFObIwEwEsg9e","vwBo7znhpLuQpxka"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1857,"5ibyd2sy6mX9LCEt",[-6],"g4Kj7LfpPw31IKqH",6,123554348,6452,"",2],["pow","OzZmAP+XSRFS91cv",6177,730536303757800766768968],["trees",17081,0,0,0,0,38],74967416832,["5ibyd2sy6mX9LCEt","JVJmsyn7iAbbzY55","g6VwJtCspMyhapNh","5BHEVCkG+R9uxReB","Jvz3fmPc1EPza6Q1","DiRXbkYvtV6cCHNP","JJSqMtDkEobD2t4E","hlVZ1ZMcBPKgvKRN","MYSvDLYSDPfT1kr/","mj9V8jO90ta7aWSo"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1858,"OzZmAP+XSRFS91cv",[-6],"L9yJhwqds1ferZlF",6,123554943,6452,"",2],["pow","1htBl3BxGLiK/RaH",6177,471638463048088639571115],["trees",17319,0,0,0,0,38],75007787008,["OzZmAP+XSRFS91cv","FwYjnSsx1Ka07eBf","B2tuEdtqY8DD0BEu","egrLNnj00zW3SGDp","zxGvek7Xsiy5phh0","UxnKaaMS3mYvmrhN","wDJvMrwCXZkzoYsF","skCyQrvJQwtiTHXw","0rN3cGgsmwmAXx+P","/XuF1BpgMXzDJ/59"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1859,"1htBl3BxGLiK/RaH",[-6],"ylTh1cVU6/1wx1Ra",6,123555054,6452,"",2],["pow","69b2lh+U7fURx/IF",6177,246084004377596318664534],["trees",17361,0,0,0,0,38],75048157184,["1htBl3BxGLiK/RaH","5ibyd2sy6mX9LCEt","Yk8KMhiWcYIIDj9H","w0WktTeBpowjXOQ/","QQ7s+EqESQSmGi5p","R9AhNZpSj9jLb5Eb","LuSevaXEOZfuwNHI","KFY4hy0iElRspXId","dUdOS6FGLybOv/JT","3jWxqxcAAigEuS8S"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1860,"69b2lh+U7fURx/IF",[-6],"rDUcLe8YV+QnMzhb",6,123555608,6452,"",2],["pow","1hpU9kuiCU08B+yx",6177,687974774589381980684109],["trees",17575,0,0,0,0,38],75088527360,["69b2lh+U7fURx/IF","OzZmAP+XSRFS91cv","ctFTVqq7qvxrX7Mi","EJfvGoehD1U0JfjR","dRPqs8VtBC5IQDRv","CYX8kz80TZmBnJ9U","VFj6z0u1HlzLkxVZ","72RG28o8moAdXZSe","DRZGas1r3udrAofE","5GhvyIdRT0rwtIty"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1861,"1hpU9kuiCU08B+yx",[-6],"BokkVkQ5Wlr4Ulpk",6,123556933,6452,"",2],["pow","Ji6tZAqZIBFeYz8d",6177,429064768737220444469797],["trees",18083,0,0,0,0,38],75128897536,["1hpU9kuiCU08B+yx","1htBl3BxGLiK/RaH","JVJmsyn7iAbbzY55","MkUdJldWKAVQM5U7","dE9SSrAesY5KQHow","A33e+sJIuO+AgdUU","00BHPoHC1s5vxRVv","VLrGAvEXj9tR6g/I","hHuzW/kD7O6WjoLd","HQzQyjjV0pTWiOtT"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1862,"Ji6tZAqZIBFeYz8d",[-6],"yyIii5wBlFD3kMf9",6,123557152,6452,"",2],["pow","HNVbiGS0yo/O43Um",6177,918586231499951699235444],["trees",18169,0,0,0,0,38],75169267712,["Ji6tZAqZIBFeYz8d","69b2lh+U7fURx/IF","FwYjnSsx1Ka07eBf","R3+JXUx1vbJ39j1+","lFrT9LMV8t7ZH+wj","UuTuV/uCXo7euUOb","WGExizlkTpwK+LK5","DY8bZ6uo3derfq/+","wi8/N23nVJRoEeYg","kdsicspSfnWHPPo2"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1863,"HNVbiGS0yo/O43Um",[-6],"xQiecZ92zJtf6JHF",6,123558859,6452,"",2],["pow","0ILMEYLt2pOCWK6u",6177,112124249206774293202729],["trees",18855,0,0,0,0,38],75209637888,["HNVbiGS0yo/O43Um","1hpU9kuiCU08B+yx","5ibyd2sy6mX9LCEt","eefUSYqSKz9CiDbi","pAhcNRCJi4TwVz2D","lGGgU+QzqB3hNyaZ","sCWt7dum1OUlunqy","BT6lcyGTMMGggbes","RAu6MtdF7lL6o0sP","+XGYKTke9OOWlqZE"]]

26> easy:balance().
this account does not yet exist
["0.00000000"]
27> FOUND A BLOCK !
absorb block ["block_plus",["block",1864,"0ILMEYLt2pOCWK6u",[-6],"Bw90LAg4sZdSqxzL",6,123562070,6452,"",2],["pow","Tm9npna2AAXqCaht",6177,327267536437568185277265],["trees",20019,0,0,0,0,38],75250008064,["0ILMEYLt2pOCWK6u","Ji6tZAqZIBFeYz8d","OzZmAP+XSRFS91cv","LOxvbqmqvriyiKOI","wbMY4RHWh2/7nH4/","+vtZLFQfXLVh6jgw","BMO4WEc+Si5exWoC","vyPQAlKX28fCAxnm","Pgbw1JeQChOSLSJW","S1AyjAhJXKAUvN7n"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1865,"Tm9npna2AAXqCaht",[-6],"DPOO+IUQfRNFJ16H",6,123562285,6452,"",2],["pow","ZVZD3NmfXEGWRJT4",6177,354988100694771871492535],["trees",20091,0,0,0,0,38],75290378240,["Tm9npna2AAXqCaht","HNVbiGS0yo/O43Um","1htBl3BxGLiK/RaH","g6VwJtCspMyhapNh","xuMbRcPQRvUN6lYx","jHsGNa69ZOdRC0HN","RKNudi912g+dE6aw","WwfvhxYOqZ8ZiXei","xUKT8EPZRbqKI1FZ","iEJWaW2/gcnoneJv"]]

27> 
27> FOUND A BLOCK !
absorb block ["block_plus",["block",1866,"ZVZD3NmfXEGWRJT4",[-6],"SOo3fZvYBqZII6cb",6,123564028,6452,"",2],["pow","BGWC2Cp7ygGzqx/l",6177,126826536030464801449808],["trees",20723,0,0,0,0,38],75330748416,["ZVZD3NmfXEGWRJT4","0ILMEYLt2pOCWK6u","69b2lh+U7fURx/IF","B2tuEdtqY8DD0BEu","VrBzK5UW6aQ9b2Lv","Pn/uE6GOVa8QGDHo","YYybhUk7OUirEwsA","0r6CGul5jKnqfW03","CCsGNCCpXy8rYy2V","MulKD8kbh9S3uTvp"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1867,"BGWC2Cp7ygGzqx/l",[-6],"YJxKfO38BVDMKZOr",6,123565183,6452,"",2],["pow","pIDR1E3gxpqZrsS+",6177,358799558529249523148387],["trees",21151,0,0,0,0,38],75371118592,["BGWC2Cp7ygGzqx/l","Tm9npna2AAXqCaht","1hpU9kuiCU08B+yx","Yk8KMhiWcYIIDj9H","OMoleFOxTKMx7jmb","AquIhQWRQR2vPLx/","hjvUW6E5y3bz4dTR","zVKwi3IFps2/v5mp","OQA1ejeToI/LOn5s","J9taDWZqglVL/GU+"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1868,"pIDR1E3gxpqZrsS+",[-6],"HBA2r6JXwtdO0N/m",6,123566827,6452,"",2],["pow","b+1fmqSaEGZ8crs1",6177,884453843132960580747645],["trees",21697,0,0,0,0,38],75411488768,["pIDR1E3gxpqZrsS+","ZVZD3NmfXEGWRJT4","Ji6tZAqZIBFeYz8d","ctFTVqq7qvxrX7Mi","mPIOCqdrj/0jg3o9","X8ccW3XQmQ68Pi++","FfuC9k3MSgVvPRBp","wgnQdQa0jclqZiOR","ZPmTAvDtGJ97zOpl","VZsW7hvQ2N45+uPm"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1869,"b+1fmqSaEGZ8crs1",[-6],"65O8XkM09QUPXHxT",6,123566924,6452,"",2],["pow","ntiqIsBQltv8QOMy",6177,234213088725091831999513],["trees",21733,0,0,0,0,38],75451858944,["b+1fmqSaEGZ8crs1","BGWC2Cp7ygGzqx/l","HNVbiGS0yo/O43Um","JVJmsyn7iAbbzY55","ub+N3nrCE84jqpBB","E+Vh1GC7BgSUVu4n","Cq6mf3v08T8xHNvQ","XquAX9gA45W+6zjT","3eUQDbdEbgJVsmWJ","xywsf4hkjcam2AoU"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1870,"ntiqIsBQltv8QOMy",[-6],"vOUkCUl3xR8HumZl",6,123568653,6452,"",2],["pow","Qcfy82T6RQjRp3tZ",6177,451551968583235669338482],["trees",22391,0,0,0,0,38],75492229120,["ntiqIsBQltv8QOMy","pIDR1E3gxpqZrsS+","0ILMEYLt2pOCWK6u","FwYjnSsx1Ka07eBf","8737BDS6gy9nvXqk","h0p8YI4ajBhTKwhf","j7baQp5or1pzzh8i","h1ENJFaY0ZzBDPWo","UKmNH9vdMZXFP9JS","dmZi4V9ZYLvMdC8f"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1871,"Qcfy82T6RQjRp3tZ",[-6],"GULWqWRqruGMAJjY",6,123568848,6452,"",2],["pow","aTg+ZQg+jkLtc3C7",6177,610276094823505014317454],["trees",22463,0,0,0,0,38],75532599296,["Qcfy82T6RQjRp3tZ","b+1fmqSaEGZ8crs1","Tm9npna2AAXqCaht","5ibyd2sy6mX9LCEt","r8eSJff8cq1yOISe","BTWoe9RO+FuCHmOL","FF2N0wn9zU9NbPhe","arI9VH3Xw4KYtYaU","v/jQWRWJNCBMymFS","CpTvXi/U8gfWyef3"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1872,"aTg+ZQg+jkLtc3C7",[-6],"IOQQCRRefsaNrozn",6,123568908,6452,"",2],["pow","mZt5om94XyYZLX9R",6177,851358076913064869609536],["trees",22487,0,0,0,0,38],75572969472,["aTg+ZQg+jkLtc3C7","ntiqIsBQltv8QOMy","ZVZD3NmfXEGWRJT4","OzZmAP+XSRFS91cv","AYElQcnK0tXeJ9pB","40IhJHGrolNHEXm9","y5Ib3gdmJsLiD2ER","niT5KX68Kv6z8hKH","06JPhdqrxbEkcFKe","QkI2NiKQUruEUaDv"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1873,"mZt5om94XyYZLX9R",[-6],"zsHQnEdLk1ordzep",6,123569689,6452,"",2],["pow","OyNoK9v+EFl6T57k",6177,535173012939311174573624],["trees",22779,0,0,0,0,38],75613339648,["mZt5om94XyYZLX9R","Qcfy82T6RQjRp3tZ","BGWC2Cp7ygGzqx/l","1htBl3BxGLiK/RaH","5BHEVCkG+R9uxReB","AGrX6ebX5Z9StVNh","3fF8tZjcFl315glL","10uFr75GyWCaiVHV","slRB1RWgDPK6o3nu","ROjYXWFFbepksL9U"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1874,"OyNoK9v+EFl6T57k",[-6],"U5o4Hhrb2Ex8An32",6,123570011,6452,"",2],["pow","KzUuqk5LY8HQYhME",6177,983643310327522415341271],["trees",22909,0,0,0,0,38],75653709824,["OyNoK9v+EFl6T57k","aTg+ZQg+jkLtc3C7","pIDR1E3gxpqZrsS+","69b2lh+U7fURx/IF","egrLNnj00zW3SGDp","oZFNDe6V0k9eB1dm","3bBa6gb9P7+W7gfM","qZ0wwdTAG0zKF9wO","gxqd2jVOdKxL1cOd","fXXkbsQaiN5ECoIx"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1875,"KzUuqk5LY8HQYhME",[-6],"EVlrpqpcALOi0f8X",6,123570669,6452,"",2],["pow","Ukl5+sI23cpPa0Sn",6177,206387363243670911940583],["trees",23135,0,0,0,0,38],75694080000,["KzUuqk5LY8HQYhME","mZt5om94XyYZLX9R","b+1fmqSaEGZ8crs1","1hpU9kuiCU08B+yx","w0WktTeBpowjXOQ/","kykVD7yrW+15Pi5M","jLT810cwd5T2+YY0","ykTaCRgLb/o9LVAT","DW+Ezk6bC4a6KMM7","SGO4QQ8OcaIJMxIU"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1876,"Ukl5+sI23cpPa0Sn",[-6],"Yusewpx3VZ60IDDJ",6,123571752,6452,"",2],["pow","I7Ys2fvVpk3ZvJ6P",6177,460287122750590063983662],["trees",23545,0,0,0,0,38],75734450176,["Ukl5+sI23cpPa0Sn","OyNoK9v+EFl6T57k","ntiqIsBQltv8QOMy","Ji6tZAqZIBFeYz8d","EJfvGoehD1U0JfjR","o6hlnVWiNZMhlE1C","TKfMCyEt0v5i2SHA","VZuiGhkYW28ZdvtL","nOlamfVvkXurvUqU","OJT62/+kIITAkW7g"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1877,"I7Ys2fvVpk3ZvJ6P",[-6],"mx0iqs5JnVcsLpf8",6,123571873,6452,"",2],["pow","F0Y8uMcUUMk6Onfw",6177,483187428833924536297158],["trees",23591,0,0,0,0,38],75774820352,["I7Ys2fvVpk3ZvJ6P","KzUuqk5LY8HQYhME","Qcfy82T6RQjRp3tZ","HNVbiGS0yo/O43Um","MkUdJldWKAVQM5U7","AVv4Dr49NhFJs/8K","fkZi3H/O1oJViCjl","DMapsP+5T8+nZ0Ud","Km+AL2GSC5BjdbP2","7Ha/AryUF9YdTfad"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1878,"F0Y8uMcUUMk6Onfw",[-6],"Av8+W66IlFox5wct",6,123572101,6452,"",2],["pow","1QY0z9PqMkKhD1gd",6177,637983284941748445707349],["trees",23673,0,0,0,0,38],75815190528,["F0Y8uMcUUMk6Onfw","Ukl5+sI23cpPa0Sn","aTg+ZQg+jkLtc3C7","0ILMEYLt2pOCWK6u","R3+JXUx1vbJ39j1+","ihNWUljUUf1gUqwb","G001veHUq6vfe4CO","7ul3rzBHMp0IoyK5","UjvVJEfheOw1K7kV","0SuVyahV/LkvSPbn"]]

27> keysFOUND A BLOCK !
absorb block ["block_plus",["block",1879,"1QY0z9PqMkKhD1gd",[-6],"HrznxZDqdVN9i3x0",6,123572335,6452,"",2],["pow","8My5VMTgRyoFOuWT",6177,754790369295679419212622],["trees",23765,0,0,0,0,38],75855560704,["1QY0z9PqMkKhD1gd","I7Ys2fvVpk3ZvJ6P","mZt5om94XyYZLX9R","Tm9npna2AAXqCaht","eefUSYqSKz9CiDbi","ZRoQpmrETX9F1Qev","y0VKSj7KDCFDr8/M","1MBpcoxw/6UEW2Sd","z84Zp9osNzaJK0pJ","JJ5yrVAzJnETD5ip"]]
FOUND A BLOCK !
absorb block ["block_plus",["block",1880,"8My5VMTgRyoFOuWT",[-6],"djdzLBGCKdMtoHP6",6,123572577,6452,"",2],["pow","zQ4eL6nXCN37kmzI",6177,533249220363368258529757],["trees",23821,0,0,0,0,38],75895930880,["8My5VMTgRyoFOuWT","F0Y8uMcUUMk6Onfw","OyNoK9v+EFl6T57k","ZVZD3NmfXEGWRJT4","LOxvbqmqvriyiKOI","rUYPiiy22FmRZtBx","rz8d/d9DVGuvDAbo","9k8NfnoceLhGyL+a","1p92muTjH0Uw/l7v","DxdApO/MPU1yPNbK"]]

27> keys:unlock("").
* 5: syntax error before: keys
27> keys:unlock("").
ok
28> easy:balance().
this account does not yet exist
["0.00000000"]
29> FOUND A BLOCK !
absorb block ["block_plus",["block",1881,"zQ4eL6nXCN37kmzI",[-6],"1glTPfRQVaULcCjj",6,123573492,6452,"",2],["pow","eG4r+77hSItkTkfU",6177,517808419427893427950220],["trees",24159,0,0,0,0,38],75936301056,["zQ4eL6nXCN37kmzI","1QY0z9PqMkKhD1gd","KzUuqk5LY8HQYhME","BGWC2Cp7ygGzqx/l","g6VwJtCspMyhapNh","BctKvDieaxmjVPd8","Br8XVaM8cSQX/8CD","VW/onsp0rjs+FX5Q","LRo3nOCqDJZj3/n/","POQlZW6ffUI42g4z"]]
key
29> keys:unlock("!!!!!").
* 2: syntax error before: keys
29> keys:unlock("!!!!!").
keys diedok

=ERROR REPORT==== 16-May-2017::12:59:30 ===
** Generic server keys terminating 
** Last message in was {'$gen_cast',{unlock,"!!!!!"}}
** When Server state == [{[],[{"State",[]}]}]
** Reason for termination == 
** {badarg,[{erlang,binary_to_term,
                    [<<208,147,47,113,75,17,7,118,22,157,119,29,22,61,144,109,
                       186,220,141,67,90,247,12,246,205,61,21,213,217,96,89,
                       168,151,142,67,79,207,129,58,129,94,255,153,20,70,54,
                       123,216,135,143,157,37,76,139,43,180,49,125,86,213,252,
                       227,116,45,9,241,128,46,186,184,110,6,68,158,62,183,65,
                       243,203,62,252,175,13,69,119,81,240,117,102,137,13,170,
                       38,115,94,115,237,163,170,104,97,219,118,132,108,1,216,
                       139,68,187,108,202,188,107,177,13,249,70,246,143,234,
                       54,84,239,70,202,168,97,19,193,169,147,63,202,250,86,
                       112,241,96,199,138,25,24,248,71,199,190,247,54,244,111,
                       177,209,199,103,161,185,111,232,192,55,172,3,108,41,46,
                       102,195,174,138,252,93,192,93,249,75,158,89,192,236,
                       138,113,170,147,52,129,249,135,134,233,94,83,173,89,
                       164,188,47,109,47,172,73,91,26,67,31,163,148,221,139,
                       228,165,92,134,188>>],
                    []},
            {encryption,sym_dec,2,[{file,"src/encryption.erl"},{line,19}]},
            {encryption,get_msg,2,[{file,"src/encryption.erl"},{line,28}]},
            {encryption,decrypt,2,[{file,"src/encryption.erl"},{line,43}]},
            {keys,handle_cast,2,[{file,"src/consensus/keys.erl"},{line,75}]},
            {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},
            {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},
            {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
30> start keys
ke
30> keys:unlock("").
* 2: syntax error before: keys
30> 
30> keys:unlock(").
ok

**Comment by zack-bitcoin** [comment]
It takes I think 200 blocks to receive your reward from mining a block.
This is the same as how bitcoin works.
