### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by andreystehno** [aeternity/testnet#88]
@zack-bitcoin 

I installed testnet on mac from `https://github.com/aeternity/testnet/blob/master/docs/compile_mac.md`

First thing I found. No installation issues

But then I tried to run tests

```
https://github.com/aeternity/testnet/blob/master/tests/channel_test.sh
```

I replaced ports to 8040, 8041. 

And got kind of issues

```
I can't handle this
```

or

```
=ERROR REPORT==== 22-May-2017::11:52:28 ===
Error in process <0.420.0> with exit value:
{[{reason,{badmatch,{error,failed_connect}}},
  {mfa,{internal_handler,handle,2}},
  {stacktrace,[{internal_handler,doit,1,
                                 [{file,"src/networking/internal_handler.erl"},
                                  {line,102}]},
               {internal_handler,handle,2,
                                 [{file,"src/networking/internal_handler.erl"},
                                  {line,16}]},
               {cowboy_handler,handler_handle,4,
                               [{file,"src/cowboy_handler.erl"},{line,111}]},
               {cowboy_protocol,execute,4,
                                [{file,"src/cowboy_protocol.erl"},
                                 {line,442}]}]},
  {req,[{socket,#Port<0.2555>},
        {transport,ranch_tcp},
        {connection,keepalive},
        {pid,<0.420.0>},
        {method,<<"POST">>},
        {version,'HTTP/1.1'},
        {peer,{{127,0,0,1},57679}},
        {host,<<"localhost">>},
        {host_info,undefined},
        {port,8041},
        {path,<<"/">>},
        {path_info,undefined},
        {qs,<<>>},
        {qs_vals,undefined},
        {bindings,[]},
        {headers,[{<<"host">>,<<"localhost:8041">>},
                  {<<"user-agent">>,<<"curl/7.51.0">>},
                  {<<"accept">>,<<"*/*">>},
                  {<<"content-length">>,<<"40">>},
                  {<<"content-type">>,
                   <<"application/x-www-form-urlencoded">>}]},
        {p_headers,[]},
        {cookies,undefined},
        {meta,[]},
        {body_state,waiting},
        {buffer,<<"[\"channel_spend\", [127,0,0,1], 3020, 27]">>},
        {multipart,undefined},
        {resp_compress,false},
        {resp_state,waiting},
        {resp_headers,[]},
        {resp_body,<<>>},
        {onresponse,undefined}]},
  {state,no_state}],
 [{cowboy_handler,handler_handle,4,
                  [{file,"src/cowboy_handler.erl"},{line,119}]},
  {cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]}
```

Could you help me to overcome it?

**Comment by zack-bitcoin** [comment]
Those are the tests that require more than 1 node.
If you read the top of the test, it explains what are the ports the nodes need.
https://github.com/aeternity/testnet/blob/master/tests/channel_test.sh

There are more tests for running on a single node:
`tester:test().`

**Comment by bilbma** [comment]
After tester:test().
17> tester:test().
constants test
sign test
encryption test
fractions test
merkel tree tests
block hashes test
block test
top, 
["block_plus",["block",9,"BisGJfAepWF/61lC",[-6],"Vh+Pjkkcy9DjdBma",1,128945520,6452,"",2],"undefined",["trees",1,0,0,0,0,72],363331584,["BisGJfAepWF/61lC","OstFj6KMFdD8q474","L44BsC/aoVPj0W51"]]top 2, 
top of sync
top returneddownloading blocks
top of sync
top returneddownloading blocks
FOUND A BLOCK !
absorb block: 9
top of sync
top returneddownloading blocks
finished syncing
top of sync
top returneddownloading blocks
FOUND A BLOCK !
absorb block: 10
top of sync
top returneddownloading blocks
["block_plus",["block",9,"BisGJfAepWF/61lC",[-6],"Vh+Pjkkcy9DjdBma",1,128945520,6452,"",2],["pow","StlHntkooNyTpVBV",6177,520932545880887804174532],["trees",1,0,0,0,0,72],363331584,["BisGJfAepWF/61lC","OstFj6KMFdD8q474","L44BsC/aoVPj0W51"]]top 3, 
spk test
txs test
** exception error: no match of right hand side value <<"BCppHfnjrr2PJEo2DSw/7hRZWGv/B4pa/gw81/3g1KSzs1DIxsqjXIm+rFVDiR/anFvO0AmETY1s26ygyUxmiys=">>
     in function  test_txs:test/0 (src/consensus/txs/test_txs.erl, line 7)
     in call from tester:test1/0 (src/consensus/tester.erl, line 33)
18> finished syncing
top of sync
top returneddownloading blocks
top of sync
top returneddownloading blocks

18> keys:load(<<"BCppHfnjrr2PJEo2DSw/7hRZWGv/B4pa/gw81/3g1KSzs1DIxsqjXIm+rFVDiR/anFvO0AmETY1s26ygyUxmiys=">>,<<"wGccpuUjL/JCME2ngcBURQgb8RMICC9LCLGwLBM08WM=">>,"abc").
** exception error: undefined function keys:load/3
19> top of sync
top returneddownloading blocks
top of sync

**Comment by zack-bitcoin** [comment]
yes, you need to control the master account to run some tests.
The master pub key is stored in src/consensus/constants.erl 
If you replace the master pub key with your pub key, then it should work.

Also, when you run tests you need to change free_constants:test_mode() to true.
it is in /src/free_constants.erl
This will make the difficulty really low so you can mine fast.
It should only take a few seconds to run the tests on a single node.
Running the tests on multiple nodes takes like 20 seconds.

I should probably re-write the tests so you don't need to control the master account to run them.
