### ISSUE TITLE
chalang/src/chalang.erl giving me rebar abort on compile and launch Ubuntu 14.04.3

### ISSUE THREAD

**Issue by StrongLLC** [aeternity/testnet#9]
I respect the project and am very excited about it!

All the best,
Norman
-=------------------------------------------------
All ran fine until this part 

UBUNTU 14.04.3 Trusty Tahr
-----------------------------------------------------------------------------------------------------
==> chalang (compile)
/home/mothership/testnet/deps/chalang/src/chalang.erl:90: syntax error before: '{'
/home/mothership/testnet/deps/chalang/src/chalang.erl:128: syntax error before: '{'
/home/mothership/testnet/deps/chalang/src/chalang.erl:2: function test/6 undefined
/home/mothership/testnet/deps/chalang/src/chalang.erl:84: function test/6 undefined
/home/mothership/testnet/deps/chalang/src/chalang.erl:113: function run3/7 undefined
/home/mothership/testnet/deps/chalang/src/chalang.erl:78: Warning: function make_tuple/2 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:80: Warning: function make_list/3 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:148: Warning: function run2/2 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:246: Warning: function run3/2 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:516: Warning: function memory/1 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:517: Warning: function memory/2 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:536: Warning: function balanced_f/2 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:552: Warning: function none_of/2 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:584: Warning: variable 'C' is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:597: Warning: function split_if/2 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:599: Warning: function split_if/3 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:609: Warning: variable 'Rest' is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:616: Warning: function split_list/2 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:618: Warning: function split_list/3 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:622: Warning: function print_stack/1 is unused
/home/mothership/testnet/deps/chalang/src/chalang.erl:625: Warning: function print_stack/2 is unused
Compiling /home/mothership/testnet/deps/chalang/src/chalang.erl failed:
ERROR: compile failed while processing /home/mothership/testnet/deps/chalang: rebar_abort
Erlang R16B03 (erts-5.10.4) [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V5.10.4  (abort with ^G)
1> {"init terminating in do_boot",{undef,[{serve,pw,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,569}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,118}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

**Comment by zack-bitcoin** [comment]
Looks like you are using an old version of erlang that doesn't know about maps.
I don't use maps very often, it wouldn't be too hard to make it backward compatible.
Here is where to install erlang https://www.erlang.org/downloads
Or you can upgrade to a more recent Ubuntu, and then just use the package manager to get erlang.
