### ISSUE TITLE
easy:sync().

### ISSUE THREAD

**Issue by MarkGriffin** [aeternity/testnet#92]
What happened to easy:sync().    ???

5> easy:sync().
** exception error: undefined function easy:sync/0
6>

**Comment by tclauss** [comment]
@MarkGriffin , easy:sync().  is obsolete now. instead, use sync:start().

**Comment by MarkGriffin** [comment]
Ok great thanks! All working ok now.

**Comment by MarkGriffin** [comment]
I just pulled the latest release and got an error with sync:start().

5> sync:start().
ok
6> top of sync
top returneddownloading blocks
trade blocksstart garbage
died!gensis maker accounts write

=ERROR REPORT==== 26-May-2017::18:49:27 ===
** Generic server block_absorber terminating
** Last message in was {'$gen_cast',
                           {doit,
                               {block_plus,
                                   {block,1,
                                       <<157,224,95,221,112,235,223,62,53,203,
                                         65,39>>,
                                       [],
                                       <<86,31,143,142,73,28,203,208,227,116,
                                         25,154>>,
                                       {2,<<"BvJuF7dkAR23xrE9uY">>},
                                       128930541,6452,<<>>,2},
                                   {pow,
                                       <<208,26,56,190,36,110,252,94,213,75,
                                         158,20>>,
                                       6177,859511419648389615360067},
                                   {trees,1,0,0,0,0,72},
                                   40370176,
                                   {neBf3XDr3z41y0En}}}}
** When Server state == []
** Reason for termination ==
** {{badrecord,block_plus},
    [{block,trees,1,[{file,"src/consensus/chain/block.erl"},{line,62}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,54}]},
     {trees,keepers,3,[{file,"src/consensus/trees/trees.erl"},{line,56}]},
     {trees,garbage,1,[{file,"src/consensus/trees/trees.erl"},{line,58}]},
     {trees,garbage,0,[{file,"src/consensus/trees/trees.erl"},{line,63}]},
     {block_absorber,handle_cast,2,
                     [{file,"src/consensus/chain/block_absorber.erl"},
                      {line,18}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]}]}
finished syncing
top of sync
top returneddownloading blocks

**Comment by tclauss** [comment]
@MarkGriffin please reinstall the testnet. now seems to work fine, for me. first sync:start(). until you see ""finished syncing"". after that you can execute mine:start().

**Comment by zack-bitcoin** [comment]
I think if you reinstall completely from github, instead of using `git pull`
That might fix it.

**Comment by Leonyxtested** [comment]
He terminado de sincronizar la blockchain y ahora me sale constantemente este mensaje.
13> sync:start().
ok
14> top of sync
top returneddownloading blocks
top of sync
top returneddownloading blocks
top of sync
top returneddownloading blocks

Mi ultimo bloque en este momento es el 8682, estoy usando el Bash de Ubuntu

**Comment by zack-bitcoin** [comment]
@Leonyxtested 
To turn sync off do this:
`sync:stop()`
That will stop the messages.

Para altar los mensajes.

**Comment by Leonyxtested** [comment]
finished syncing
top of sync
top returneddownloading blocks

=ERROR REPORT==== 8-Jun-2017::17:19:24 ===
Error in process <0.514.0> with exit value:
{{badmatch,false},
 [{block,check1,1,[{file,"src/consensus/chain/block.erl"},{line,270}]},
  {download_blocks,trade_blocks,4,
                   [{file,"src/consensus/download_blocks.erl"},{line,87}]},
  {download_blocks,'-sync/3-fun-1-',4,
                   [{file,"src/consensus/download_blocks.erl"},{line,57}]}]}
top of sync
top returneddownloading blocks

=ERROR REPORT==== 8-Jun-2017::17:19:25 ===
Error in process <0.517.0> with exit value:
{{badmatch,false},
 [{block,check1,1,[{file,"src/consensus/chain/block.erl"},{line,270}]},
  {download_blocks,trade_blocks,4,
                   [{file,"src/consensus/download_blocks.erl"},{line,87}]},
  {download_blocks,'-sync/3-fun-1-',4,
                   [{file,"src/consensus/download_blocks.erl"},{line,57}]}]}
7> sync:stop().
ok
8> easy:height().
1

**Comment by zack-bitcoin** [comment]
@Leonyxtested if you download a fresh copy of the code from github, it should solve this error.
