### ISSUE TITLE
mine:start(). fail: talk helper fail

### ISSUE THREAD

**Issue by tclauss** [aeternity/testnet#98]
@zack-bitcoin mine:start(). seems to fail again ...

testnet@aeternity:~/testnet$ sh start.sh 
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:3:3] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.2.1  (abort with ^G)
1> start keys
start topgensis maker accounts write 
tx pool started
starting secretsstart server
keys:new("pwd").
ok
2> keys:unlock("pwd").
ok
3> easy:address().
<<"Fi4o5ktyWo1RnzsPLD">>
4> 
5> easy:balance().
0
6> **sync:start().**
ok
7> top of sync
top returneddownloading blocks
trade blocksabsorb block: 1
absorb block: 2

....

absorb block: 98
absorb block: 99
absorb block: 100
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
absorb_txs accounts write 
absorb block: 101
absorb block: 102

...

absorb block: 196
absorb block: 197
absorb block: 198
absorb block: 199
check2 garbage absorb block: 200
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
absorb block: 201
absorb block: 202
absorb block: 203
absorb block: 204
absorb block: 205
absorb_txs accounts write 
absorb block: 206

.....

absorb block: 496
absorb block: 497
absorb block: 498
absorb block: 499
check2 garbage absorb block: 500
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
absorb block: 501
absorb block: 502
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
**finished syncing**
top of sync
top of sync
talk helper fail

.....

talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
easy:off().
block_hashes died!secrets died!testnet@aeternity:~/testnet$ sh start.sh 
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:3:3] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.2.1  (abort with ^G)
1> start keys
start topgensis maker accounts write 
tx pool started
starting secretsstart server
easy:address().
<<"Fi4o5ktyWo1RnzsPLD">>
2> keys:unlock("pwd").
ok
3> **mine:start().**
start mining with 3 cores.
top of sync
ok
4> top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks
top of sync
top of sync
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk helper fail
talk error 
top returneddownloading blocks

**Comment by zack-bitcoin** [comment]
It seems that after you are done syncing, these messages keep appearing. 
Everything is functioning correctly. I will try to stop the messages.

**Comment by tclauss** [comment]
start the mining process and is shown again and again the same message, don't find any block ....

**Comment by Leonyxtested** [comment]
He encontrado bloques pero al mirar mi balance aparece,.
12> easy:balance().
this account does not yet exist
0

Estoy usando el Bash de Ubuntu.

**Comment by rionda2** [comment]
I have the same problem.

I found some blocks but when I check my balance this is empty.

![sin titulo](https://user-images.githubusercontent.com/29264753/26904711-92bbf85a-4be3-11e7-9700-043b8e0230fd.jpg)

**Comment by rionda2** [comment]
I have the same problem.

I found some blocks but when I write easy:balance(). it says that it's empty.
And if I ask if mine:is_on(). it gives me an **exception error

![sin titulo](https://user-images.githubusercontent.com/29264753/26904863-63e32a16-4be4-11e7-92f3-60a0dedca1f8.jpg)

**Comment by zack-bitcoin** [comment]
@rionda2 
`mine:is_on` was changed to `mine:status()`, so that it would be more consistent with other libraries.
it takes 200 blocks for your block reward to mature. You don't have access to the coins until 200 blocks after the time when you started mining.
